@extends('oresamsub.layouts.authapp')
@section('title', 'Create account · '.(session('affiliate')->name ?? 'Customer account'))
@section('content')
<x-customer-auth.shell title="Create your account" description="Set up your secure customer profile in a few moments." :affiliate="session('affiliate')" :site-logo="$site_logo ?? null" wide>
    <form method="POST" action="{{ route('store2') }}" x-data="{ showPassword: false, showConfirm: false, submitting: false }" @submit="submitting = true" class="auth-grid auth-grid--two">
        @csrf
        <div class="auth-field"><label for="fullname">Full name</label><input class="auth-input" type="text" name="fullname" id="fullname" value="{{ old('fullname') }}" autocomplete="name" placeholder="Firstname Lastname" required><x-input-error :messages="$errors->get('fullname')" class="auth-error" /></div>
        <div class="auth-field"><label for="username">Username</label><input class="auth-input" type="text" name="username" id="username" value="{{ old('username') }}" autocomplete="username" required><x-input-error :messages="$errors->get('username')" class="auth-error" /></div>
        <div class="auth-field"><label for="phone_number">Phone number</label><input class="auth-input" type="tel" name="phone_number" id="phone_number" value="{{ old('phone_number') }}" autocomplete="tel" inputmode="tel" placeholder="08012345678" required><x-input-error :messages="$errors->get('phone_number')" class="auth-error" /></div>
        <div class="auth-field"><label for="email">Email address</label><input class="auth-input" type="email" name="email" id="email" value="{{ old('email') }}" autocomplete="email" inputmode="email" required><x-input-error :messages="$errors->get('email')" class="auth-error" /></div>
        <div class="auth-field auth-span-two"><label for="upline_referral_phone_number">Referral phone <span class="font-normal text-slate-400">(optional)</span></label><input class="auth-input" type="tel" name="upline_referral_phone_number" id="upline_referral_phone_number" value="{{ $upline ?? old('upline_referral_phone_number') }}" inputmode="tel" placeholder="Upline's phone number" @readonly(!empty($upline))><x-input-error :messages="$errors->get('upline_referral_phone_number')" class="auth-error" /></div>
        <div class="auth-field auth-span-two"><label for="pin">Transaction PIN</label><input class="auth-input" type="password" name="pin" id="pin" maxlength="4" inputmode="numeric" autocomplete="new-password" placeholder="Enter 4-digit PIN" required><x-input-error :messages="$errors->get('pin')" class="auth-error" /></div>
        <div class="auth-field"><label for="password">Password</label><div class="auth-input-wrap"><input class="auth-input" :type="showPassword ? 'text' : 'password'" name="password" id="password" autocomplete="new-password" required><button class="auth-reveal" type="button" @click="showPassword = !showPassword" x-text="showPassword ? 'Hide' : 'Show'"></button></div><x-input-error :messages="$errors->get('password')" class="auth-error" /></div>
        <div class="auth-field"><label for="password_confirmation">Confirm password</label><div class="auth-input-wrap"><input class="auth-input" :type="showConfirm ? 'text' : 'password'" name="password_confirmation" id="password_confirmation" autocomplete="new-password" required><button class="auth-reveal" type="button" @click="showConfirm = !showConfirm" x-text="showConfirm ? 'Hide' : 'Show'"></button></div><x-input-error :messages="$errors->get('password_confirmation')" class="auth-error" /></div>
        <button class="auth-button auth-span-two" type="submit" :disabled="submitting"><span x-show="!submitting">Create account</span><span x-show="submitting" x-cloak>Creating account…</span></button>
    </form>
    <p class="auth-footer">Already have an account? <a class="auth-link" href="{{ route('login') }}">Sign in</a></p>
</x-customer-auth.shell>
@endsection
