@extends('parent-admin.layouts.app')
@section('title', 'Edit product plan')
@section('heading', 'Edit product plan')
@php($primaryRoute = $plan->providerRoutes->firstWhere('priority', 1))
@section('content')
<div class="space-y-5">
    <a href="{{ route('parent-admin.product-plans.index') }}" class="text-sm font-semibold text-blue-600">← Product plans</a>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <section class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950">
        <h2 class="font-semibold">Airtime setup guide</h2>
        <p class="mt-2">For airtime, enter costs and reseller prices per ₦1,000 face value. Example: a 1.96% upstream discount means a provider cost of ₦980.40; an affiliate acquisition discount of 0.80% means a reseller price of ₦992.00.</p>
        <p class="mt-2">Use <strong>Percentage</strong> profit mode. Leave maximum profit blank unless you intentionally want a stricter customer-discount ceiling. The same percentages then scale safely to any airtime amount entered by a customer.</p>
        <p class="mt-2 text-xs text-amber-800">For fixed-value services such as data and cable plans, enter their actual per-plan naira costs and use Flat mode where appropriate.</p>
    </section>
    <form method="POST" action="{{ route('parent-admin.product-plans.configuration.update', $plan) }}" class="space-y-5">@csrf @method('PUT')
        <section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-semibold">Plan details</h2><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <label class="text-sm">Name<input name="product_plan_name" value="{{ old('product_plan_name', $plan->product_plan_name) }}" required class="mt-1 w-full rounded-xl border-slate-200"></label>
            <label class="text-sm">Category<select name="product_plan_category_id" required class="mt-1 w-full rounded-xl border-slate-200">@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int) old('product_plan_category_id', $plan->product_plan_category_id) === $category->id)>{{ $category->product_plan_category_name }} · {{ $category->network?->network_name ?: $category->product?->product_name }}</option>@endforeach</select></label>
            @foreach(['api_id'=>'Internal reference','cost_price'=>'Provider cost','admin_cost_price'=>'Admin/reference cost','data_size_in_mb'=>'Data size MB','validity_in_days'=>'Validity days'] as $field => $label)<label class="text-sm">{{ $label }}<input name="{{ $field }}" value="{{ old($field, $plan->{$field}) }}" @if($field === 'cost_price') required @endif type="{{ $field === 'api_id' ? 'text' : 'number' }}" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label>@endforeach
            <label class="text-sm">Profit mode<select name="profit_category" class="mt-1 w-full rounded-xl border-slate-200"><option value="flat" @selected(old('profit_category', $plan->profit_category) === 'flat')>Flat</option><option value="percent" @selected(old('profit_category', $plan->profit_category) === 'percent')>Percentage</option></select></label>
        </div></section>
        <section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-semibold">Primary provider route</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm">Connection<select name="route[parent_provider_connection_id]" class="mt-1 w-full rounded-xl border-slate-200"><option value="">No route</option>@foreach($connections as $connection)<option value="{{ $connection->id }}" @selected((int) old('route.parent_provider_connection_id', $primaryRoute?->parent_provider_connection_id) === $connection->id)>{{ $connection->name }}</option>@endforeach</select></label><label class="text-sm">Provider external plan ID<input name="route[provider_plan_id]" value="{{ old('route.provider_plan_id', $primaryRoute?->provider_plan_id) }}" class="mt-1 w-full rounded-xl border-slate-200"></label></div></section>
        <section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-semibold">Reseller prices</h2><div class="mt-4 grid gap-4 md:grid-cols-3">@foreach($levels as $index => $level)@php($price = $plan->parentPrices->firstWhere('parent_reseller_level_id', $level->id))<div class="rounded-xl bg-slate-50 p-4"><strong>{{ $level->name }}</strong><input type="hidden" name="prices[{{ $index }}][parent_reseller_level_id]" value="{{ $level->id }}"><label class="mt-2 block text-xs">Selling price<input name="prices[{{ $index }}][selling_price]" value="{{ old("prices.{$index}.selling_price", $price?->selling_price) }}" type="number" min="0" step=".01" class="mt-1 w-full rounded-lg border-slate-200"></label><label class="mt-2 block text-xs">Maximum profit<input name="prices[{{ $index }}][max_profit]" value="{{ old("prices.{$index}.max_profit", $price?->max_profit) }}" type="number" min="0" step=".01" class="mt-1 w-full rounded-lg border-slate-200"></label></div>@endforeach</div></section>
        <input type="hidden" name="commission_feature" value="{{ (int) $plan->commission_feature }}"><input type="hidden" name="upline_commission_option" value="{{ $plan->upline_commission_option ?: 'flat' }}"><input type="hidden" name="upline_flat_commission" value="{{ $plan->upline_flat_commission ?: 0 }}"><input type="hidden" name="upline_percentage_commission" value="{{ $plan->upline_percentage_commission ?: 0 }}"><input type="hidden" name="upline_commission_cap" value="{{ $plan->upline_commission_cap ?: 1000 }}">
        <div class="flex flex-wrap justify-between gap-4 rounded-2xl bg-white p-5 shadow-sm"><div class="flex gap-5">@foreach(['visibility'=>'Active','affiliate_visibility'=>'Affiliates','public_visibility'=>'Public'] as $field => $label)<input type="hidden" name="{{ $field }}" value="0"><label><input name="{{ $field }}" value="1" type="checkbox" @checked(old($field, $plan->{$field}))> {{ $label }}</label>@endforeach</div><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Save full configuration</button></div>
    </form>
</div>
@endsection
