@extends('parent-admin.layouts.app')

@section('title', 'Product plans')
@section('heading', 'Manage product plans')

@section('content')
<div class="space-y-5" x-data="{ mode: 'single' }">
    <div class="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Only plans owned by <strong>{{ auth('parent_admin')->user()->parentBusiness->name }}</strong> appear here. Global categories are shared; provider routing and reseller prices belong to this parent.</div>
    @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p class="font-semibold">Please correct the following:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">CSV plan migration</h2><p class="text-sm text-slate-500">Parent-aware IDs and a preview protect the import.</p></div><a href="{{ route('parent-admin.product-plans.import.template') }}" class="rounded-xl border px-4 py-2 text-sm font-semibold">Download template</a></div><form method="POST" enctype="multipart/form-data" action="{{ route('parent-admin.product-plans.import.preview') }}" class="mt-4 flex gap-3">@csrf<input type="file" name="plans_csv" accept=".csv" required class="rounded-xl border p-2"><button class="rounded-xl bg-blue-600 px-4 py-2 text-white">Preview</button></form>@if(session('import_errors'))<div class="mt-3 text-sm text-red-700">@foreach(session('import_errors') as $line=>$error)<p>Row {{ $line }}: {{ $error }}</p>@endforeach</div>@endif</section>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="text-lg font-semibold">Add product plan</h2><p class="text-sm text-slate-500">Create one complete plan or submit several plans atomically.</p></div><div class="flex rounded-xl bg-slate-100 p-1"><button type="button" @click="mode='single'" class="rounded-lg px-4 py-2 text-sm font-semibold" :class="mode==='single'?'bg-white shadow-sm':'text-slate-500'">Single plan</button><button type="button" @click="mode='bulk'" class="rounded-lg px-4 py-2 text-sm font-semibold" :class="mode==='bulk'?'bg-white shadow-sm':'text-slate-500'">Bulk addition</button></div></div>
        @if($connections->isEmpty())<div class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">No approved provider connection is available. You can save hidden drafts, but an external parent cannot activate a plan until a connection is approved.</div>@endif

        <form method="POST" action="{{ route('parent-admin.product-plans.store') }}" x-show="mode==='single'" class="mt-6 space-y-6">
            @csrf
            <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <label class="text-sm font-medium">Plan name<input name="product_plan_name" value="{{ old('product_plan_name') }}" required class="mt-1 w-full rounded-xl border-slate-200" placeholder="MTN SME 1GB"></label>
                <label class="text-sm font-medium">Global category<select name="product_plan_category_id" required class="mt-1 w-full rounded-xl border-slate-200"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('product_plan_category_id') === (string) $category->id)>{{ $category->product_plan_category_name }} · {{ $category->network?->network_name ?: ($category->product?->product_name ?: 'General') }}</option>@endforeach</select></label>
                <label class="text-sm font-medium">Internal reference (optional)<input name="api_id" value="{{ old('api_id') }}" class="mt-1 w-full rounded-xl border-slate-200" placeholder="PAUL-MTN-1GB"></label>
                <label class="text-sm font-medium">Provider cost<input name="cost_price" value="{{ old('cost_price') }}" required type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label>
                <label class="text-sm font-medium">Admin/reference cost<input name="admin_cost_price" value="{{ old('admin_cost_price') }}" type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label>
                <label class="text-sm font-medium">Data size in MB<input name="data_size_in_mb" value="{{ old('data_size_in_mb') }}" type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label>
                <label class="text-sm font-medium">Validity in days<input name="validity_in_days" value="{{ old('validity_in_days') }}" type="number" min="0" class="mt-1 w-full rounded-xl border-slate-200"></label>
                <label class="text-sm font-medium">Profit mode<select name="profit_category" class="mt-1 w-full rounded-xl border-slate-200"><option value="flat" @selected(old('profit_category', 'flat') === 'flat')>Flat profit</option><option value="percent" @selected(old('profit_category') === 'percent')>Percentage profit</option></select></label>
            </div>

            <div class="rounded-2xl border border-slate-200 p-5"><h3 class="font-semibold">Primary provider mapping</h3><p class="mt-1 text-sm text-slate-500">The external plan ID is the value the selected provider expects during processing.</p><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm font-medium">Approved provider connection<select name="route[parent_provider_connection_id]" class="mt-1 w-full rounded-xl border-slate-200"><option value="">No route — save as draft</option>@foreach($connections as $connection)<option value="{{ $connection->id }}" @selected((string) old('route.parent_provider_connection_id') === (string) $connection->id)>{{ $connection->name }} · {{ $connection->providerConnection?->name }}</option>@endforeach</select></label><label class="text-sm font-medium">Provider external plan ID<input name="route[provider_plan_id]" value="{{ old('route.provider_plan_id') }}" class="mt-1 w-full rounded-xl border-slate-200" placeholder="111"></label></div></div>

            <div class="rounded-2xl border border-slate-200 p-5"><h3 class="font-semibold">Reseller acquisition prices</h3><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($levels as $index => $level)<div class="rounded-xl bg-slate-50 p-4"><p class="text-sm font-semibold">{{ $level->name }}</p><input type="hidden" name="prices[{{ $index }}][parent_reseller_level_id]" value="{{ $level->id }}"><div class="mt-3 grid grid-cols-2 gap-2"><label class="text-xs text-slate-500">Selling price<input name="prices[{{ $index }}][selling_price]" value="{{ old("prices.{$index}.selling_price") }}" type="number" min="0" step="0.01" class="mt-1 w-full rounded-lg border-slate-200"></label><label class="text-xs text-slate-500">Maximum profit<input name="prices[{{ $index }}][max_profit]" value="{{ old("prices.{$index}.max_profit") }}" type="number" min="0" step="0.01" class="mt-1 w-full rounded-lg border-slate-200"></label></div></div>@empty<p class="text-sm text-slate-500">Create reseller levels from the pricing workspace.</p>@endforelse</div></div>

            <details class="rounded-2xl border border-slate-200 p-5"><summary class="cursor-pointer font-semibold">Commission settings</summary><input type="hidden" name="commission_feature" value="0"><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label class="text-sm">Mode<select name="upline_commission_option" class="mt-1 w-full rounded-xl border-slate-200"><option value="flat">Flat</option><option value="percent">Percentage</option></select></label><label class="text-sm">Flat commission<input name="upline_flat_commission" value="{{ old('upline_flat_commission', 0) }}" type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-sm">Percentage<input name="upline_percentage_commission" value="{{ old('upline_percentage_commission', 0) }}" type="number" min="0" max="100" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-sm">Cap<input name="upline_commission_cap" value="{{ old('upline_commission_cap', 1000) }}" type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label></div><label class="mt-4 flex gap-2 text-sm"><input name="commission_feature" value="1" type="checkbox" @checked(old('commission_feature', true))> Enable commission</label></details>

            <div class="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-slate-50 p-4"><div class="flex flex-wrap gap-5 text-sm">@foreach(['visibility'=>'Active','affiliate_visibility'=>'Visible to affiliates','public_visibility'=>'Publicly visible'] as $field=>$label)<input type="hidden" name="{{ $field }}" value="0"><label><input name="{{ $field }}" value="1" type="checkbox" @checked(old($field, false))> {{ $label }}</label>@endforeach</div><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Add product plan</button></div>
        </form>

        <form method="POST" action="{{ route('parent-admin.product-plans.bulk-store') }}" x-show="mode==='bulk'" x-data="bulkProductPlans(@js($categories), @js($connections), @js($levels))" class="mt-6 space-y-4">@csrf
            <div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Every row is validated before saving. If one row is invalid, no plan is created.</div>
            <template x-for="(row,i) in rows" :key="row.id"><article class="rounded-2xl border p-4"><div class="flex justify-between"><strong x-text="`Plan ${i+1}`"></strong><button type="button" x-show="rows.length>1" @click="rows.splice(i,1)" class="text-sm text-red-600">Remove</button></div><div class="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input :name="`plans[${i}][product_plan_name]`" required placeholder="Plan name" class="rounded-xl border-slate-200"><select :name="`plans[${i}][product_plan_category_id]`" required class="rounded-xl border-slate-200"><option value="">Category</option><template x-for="category in categories"><option :value="category.id" x-text="category.product_plan_category_name"></option></template></select><input :name="`plans[${i}][cost_price]`" required type="number" min="0" step=".01" placeholder="Provider cost" class="rounded-xl border-slate-200"><select :name="`plans[${i}][route][parent_provider_connection_id]`" class="rounded-xl border-slate-200"><option value="">Provider route</option><template x-for="connection in connections"><option :value="connection.id" x-text="connection.name"></option></template></select><input :name="`plans[${i}][route][provider_plan_id]`" placeholder="External plan ID" class="rounded-xl border-slate-200"><input :name="`plans[${i}][api_id]`" placeholder="Internal reference" class="rounded-xl border-slate-200"><input :name="`plans[${i}][data_size_in_mb]`" type="number" min="0" placeholder="Data MB" class="rounded-xl border-slate-200"><input :name="`plans[${i}][validity_in_days]`" type="number" min="0" placeholder="Validity days" class="rounded-xl border-slate-200"></div><input type="hidden" :name="`plans[${i}][profit_category]`" value="flat"><input type="hidden" :name="`plans[${i}][visibility]`" :value="row.visibility?1:0"><input type="hidden" :name="`plans[${i}][affiliate_visibility]`" :value="row.affiliate_visibility?1:0"><input type="hidden" :name="`plans[${i}][public_visibility]`" :value="row.public_visibility?1:0"><div class="mt-3 flex gap-4 text-xs"><label><input type="checkbox" x-model="row.visibility"> Active</label><label><input type="checkbox" x-model="row.affiliate_visibility"> Affiliates</label><label><input type="checkbox" x-model="row.public_visibility"> Public</label></div><div class="mt-3 grid gap-2 md:grid-cols-3"><template x-for="(level,j) in levels"><label class="text-xs"><span x-text="level.name"></span><input type="hidden" :name="`plans[${i}][prices][${j}][parent_reseller_level_id]`" :value="level.id"><input :name="`plans[${i}][prices][${j}][selling_price]`" type="number" min="0" step=".01" class="mt-1 w-full rounded-lg border-slate-200"></label></template></div></article></template>
            <div class="flex justify-between"><button type="button" @click="rows.push({id:crypto.randomUUID()})" class="rounded-xl border px-4 py-2">Add another row</button><button class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Create plans</button></div>
        </form>
    </section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b p-5"><h2 class="font-semibold">Parent product plans</h2><p class="text-sm text-slate-500">{{ $plans->total() }} plans</p></div><div class="overflow-x-auto"><table class="w-full min-w-[1100px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-4">Plan</th><th class="p-4">Category</th><th class="p-4">Cost</th><th class="p-4">Route</th><th class="p-4">Availability</th><th class="p-4"></th></tr></thead><tbody class="divide-y">@forelse($plans as $plan)@php($formId="plan-{$plan->id}")<tr><td class="p-4"><input form="{{ $formId }}" name="product_plan_name" value="{{ $plan->product_plan_name }}" class="w-56 rounded-lg border-slate-200"><p class="text-xs text-slate-400">{{ $plan->api_id }}</p></td><td class="p-4"><select form="{{ $formId }}" name="product_plan_category_id" class="w-64 rounded-lg border-slate-200">@foreach($categories as $category)<option value="{{ $category->id }}" @selected($plan->product_plan_category_id===$category->id)>{{ $category->product_plan_category_name }}</option>@endforeach</select></td><td class="p-4"><input form="{{ $formId }}" name="cost_price" value="{{ $plan->cost_price }}" type="number" min="0" step=".01" class="w-28 rounded-lg border-slate-200"></td><td class="p-4">{{ $plan->providerRoutes->first()?->provider_plan_id ?: 'Draft — no route' }}</td><td class="p-4">@foreach(['visibility'=>'Active','affiliate_visibility'=>'Affiliates','public_visibility'=>'Public'] as $field=>$label)<input form="{{ $formId }}" type="hidden" name="{{ $field }}" value="0"><label class="block text-xs"><input form="{{ $formId }}" name="{{ $field }}" value="1" type="checkbox" @checked($plan->{$field})> {{ $label }}</label>@endforeach</td><td class="p-4"><div class="flex items-center gap-2"><form id="{{ $formId }}" method="POST" action="{{ route('parent-admin.product-plans.update',$plan) }}">@csrf @method('PATCH')<button class="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Save</button></form><a href="{{ route('parent-admin.product-plans.edit', $plan) }}" class="rounded-lg border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700">Edit</a></div></td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No product plans found.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $plans->links() }}</div></section>
</div>
@endsection

@push('scripts')
<script>document.addEventListener('alpine:init',()=>Alpine.data('bulkProductPlans',(categories,connections,levels)=>({categories,connections,levels,rows:[{id:crypto.randomUUID(),visibility:false,affiliate_visibility:false,public_visibility:false}]})))</script>
@endpush
