@extends('parent-admin.layouts.app')

@section('title', 'Product plans')
@section('heading', 'Manage product plans')

@section('content')
<div x-data="parentPlans()" x-init="load()" class="space-y-5">
    <div class="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Only plans owned by <strong>{{ auth('parent_admin')->user()->parentBusiness->name }}</strong> appear here. Global categories are selected, while provider mapping and reseller prices belong to this parent.</div>
    <div x-show="notice" class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800" x-text="notice"></div>
    <div x-show="error" class="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700" x-text="error"></div>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="text-lg font-semibold">Add product plan</h2><p class="text-sm text-slate-500">Create one complete plan or add several plans in a single atomic batch.</p></div><div class="flex rounded-xl bg-slate-100 p-1"><button type="button" @click="mode='single'" class="rounded-lg px-4 py-2 text-sm font-semibold" :class="mode==='single'?'bg-white text-slate-950 shadow-sm':'text-slate-500'">Single plan</button><button type="button" @click="openBulk()" class="rounded-lg px-4 py-2 text-sm font-semibold" :class="mode==='bulk'?'bg-white text-slate-950 shadow-sm':'text-slate-500'">Bulk addition</button></div></div>

        <div x-show="connections.length===0" class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">No approved provider connection is available. You can save hidden drafts, but an external parent cannot activate a plan until a connection is approved.</div>

        <form x-show="mode==='single'" @submit.prevent="createPlan" class="mt-6 space-y-6">
            <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                <label class="text-sm font-medium">Plan name<input x-model="form.product_plan_name" required class="mt-1 w-full rounded-xl border-slate-200" placeholder="MTN SME 1GB"></label>
                <label class="text-sm font-medium">Global category<select x-model="form.product_plan_category_id" required class="mt-1 w-full rounded-xl border-slate-200"><option value="">Select category</option><template x-for="category in categories" :key="category.id"><option :value="category.id" x-text="categoryLabel(category)"></option></template></select></label>
                <label class="text-sm font-medium">Internal/API reference<input x-model="form.api_id" class="mt-1 w-full rounded-xl border-slate-200" placeholder="Optional internal ID"></label>
                <label class="text-sm font-medium">Provider cost<input x-model="form.cost_price" required type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200" placeholder="200.00"></label>
                <label class="text-sm font-medium">Admin/reference cost<input x-model="form.admin_cost_price" type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200" placeholder="Optional"></label>
                <label class="text-sm font-medium">Data size in MB<input x-model="form.data_size_in_mb" type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200" placeholder="1024"></label>
                <label class="text-sm font-medium">Validity in days<input x-model="form.validity_in_days" type="number" min="0" class="mt-1 w-full rounded-xl border-slate-200" placeholder="30"></label>
                <label class="text-sm font-medium">Profit mode<select x-model="form.profit_category" class="mt-1 w-full rounded-xl border-slate-200"><option value="flat">Flat profit</option><option value="percent">Percentage profit</option></select></label>
            </div>

            <div class="rounded-2xl border border-slate-200 p-5"><h3 class="font-semibold">Primary provider mapping</h3><p class="mt-1 text-sm text-slate-500">The external plan ID is the identifier this provider expects during purchase processing.</p><div class="mt-4 grid gap-4 md:grid-cols-2"><label class="text-sm font-medium">Approved provider connection<select x-model="form.route.parent_provider_connection_id" class="mt-1 w-full rounded-xl border-slate-200"><option value="">No route — save as draft</option><template x-for="connection in connections" :key="connection.id"><option :value="connection.id" x-text="`${connection.name} · ${connection.provider_connection?.name||'Provider'}`"></option></template></select></label><label class="text-sm font-medium">Provider external plan ID<input x-model="form.route.provider_plan_id" class="mt-1 w-full rounded-xl border-slate-200" placeholder="PAULTECHS-MTN-1GB"></label></div></div>

            <div class="rounded-2xl border border-slate-200 p-5"><h3 class="font-semibold">Reseller acquisition prices</h3><p class="mt-1 text-sm text-slate-500">Provide a selling price for every active level before activating an external-parent plan.</p><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><template x-for="(price,index) in form.prices" :key="price.parent_reseller_level_id"><div class="rounded-xl bg-slate-50 p-4"><p class="text-sm font-semibold" x-text="levelName(price.parent_reseller_level_id)"></p><div class="mt-3 grid grid-cols-2 gap-2"><label class="text-xs text-slate-500">Selling price<input x-model="price.selling_price" type="number" min="0" step="0.01" class="mt-1 w-full rounded-lg border-slate-200"></label><label class="text-xs text-slate-500">Maximum profit<input x-model="price.max_profit" type="number" min="0" step="0.01" class="mt-1 w-full rounded-lg border-slate-200" placeholder="Optional"></label></div></div></template><p x-show="levels.length===0" class="text-sm text-slate-500">Create at least one reseller level from the pricing workspace.</p></div></div>

            <details class="rounded-2xl border border-slate-200 p-5"><summary class="cursor-pointer font-semibold">Commission settings</summary><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label class="text-sm font-medium">Commission mode<select x-model="form.upline_commission_option" class="mt-1 w-full rounded-xl border-slate-200"><option value="flat">Flat</option><option value="percent">Percentage</option></select></label><label class="text-sm font-medium">Flat commission<input x-model="form.upline_flat_commission" type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-sm font-medium">Percentage<input x-model="form.upline_percentage_commission" type="number" min="0" max="100" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-sm font-medium">Commission cap<input x-model="form.upline_commission_cap" type="number" min="0" step="0.01" class="mt-1 w-full rounded-xl border-slate-200"></label></div><label class="mt-4 flex items-center gap-2 text-sm"><input x-model="form.commission_feature" type="checkbox"> Enable commission</label></details>

            <div class="flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-slate-50 p-4"><div class="flex flex-wrap gap-5 text-sm"><label><input x-model="form.visibility" type="checkbox"> Active</label><label><input x-model="form.affiliate_visibility" type="checkbox"> Visible to affiliates</label><label><input x-model="form.public_visibility" type="checkbox"> Publicly visible</label></div><button :disabled="saving" class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-50" x-text="saving?'Creating…':'Add product plan'"></button></div>
        </form>

        <div x-show="mode==='bulk'" class="mt-6 space-y-4">
            <div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Every row is validated before saving. If one row is invalid, no plan in the batch is created.</div>
            <template x-for="(row,rowIndex) in bulkPlans" :key="row.client_id"><article class="rounded-2xl border border-slate-200 p-5"><div class="flex items-center justify-between"><h3 class="font-semibold" x-text="`Plan ${rowIndex+1}`"></h3><button type="button" @click="removeBulkRow(rowIndex)" x-show="bulkPlans.length>1" class="text-sm font-semibold text-red-600">Remove</button></div><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
                <input x-model="row.product_plan_name" placeholder="Plan name" class="rounded-xl border-slate-200">
                <select x-model="row.product_plan_category_id" class="rounded-xl border-slate-200"><option value="">Global category</option><template x-for="category in categories" :key="category.id"><option :value="category.id" x-text="categoryLabel(category)"></option></template></select>
                <input x-model="row.route.provider_plan_id" placeholder="Provider external plan ID" class="rounded-xl border-slate-200">
                <select x-model="row.route.parent_provider_connection_id" class="rounded-xl border-slate-200"><option value="">Approved provider</option><template x-for="connection in connections" :key="connection.id"><option :value="connection.id" x-text="connection.name"></option></template></select>
                <input x-model="row.api_id" placeholder="Internal/API reference" class="rounded-xl border-slate-200">
                <input x-model="row.cost_price" type="number" min="0" step="0.01" placeholder="Provider cost" class="rounded-xl border-slate-200">
                <input x-model="row.data_size_in_mb" type="number" min="0" step="0.01" placeholder="Data size MB" class="rounded-xl border-slate-200">
                <input x-model="row.validity_in_days" type="number" min="0" placeholder="Validity days" class="rounded-xl border-slate-200">
            </div><div class="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><template x-for="price in row.prices" :key="price.parent_reseller_level_id"><label class="rounded-xl bg-slate-50 p-3 text-xs font-semibold"><span x-text="levelName(price.parent_reseller_level_id)"></span><input x-model="price.selling_price" type="number" min="0" step="0.01" placeholder="Selling price" class="mt-2 w-full rounded-lg border-slate-200 font-normal"></label></template></div><div class="mt-4 flex flex-wrap gap-4 text-xs"><label><input x-model="row.visibility" type="checkbox"> Active</label><label><input x-model="row.affiliate_visibility" type="checkbox"> Affiliates</label><label><input x-model="row.public_visibility" type="checkbox"> Public</label></div></article></template>
            <div class="flex flex-wrap justify-between gap-3"><button type="button" @click="addBulkRow" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Add another row</button><button type="button" @click="createBulk" :disabled="saving" class="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-50" x-text="saving?'Creating batch…':`Create ${bulkPlans.length} plans`"></button></div>
        </div>
    </section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 class="font-semibold">Parent product plans</h2><p class="text-sm text-slate-500" x-text="paginationText"></p></div><input x-model="search" type="search" placeholder="Search this page" class="w-full rounded-xl border-slate-200 sm:w-72"></div>
        <div x-show="loading" class="p-8 text-center text-sm text-slate-500">Loading product plans…</div>
        <div x-show="!loading" class="overflow-x-auto"><table class="w-full min-w-[1250px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-4">Plan</th><th class="p-4">Global category</th><th class="p-4">Provider cost</th><th class="p-4">Primary route</th><th class="p-4">Validity</th><th class="p-4">Availability</th><th class="p-4"></th></tr></thead><tbody class="divide-y"><template x-for="plan in filteredPlans" :key="plan.id"><tr>
            <td class="p-4"><input x-model="plan.product_plan_name" class="w-56 rounded-lg border-slate-200"><p class="mt-1 text-xs text-slate-400" x-text="plan.api_id||''"></p></td>
            <td class="p-4"><select x-model="plan.product_plan_category_id" class="w-64 rounded-lg border-slate-200"><template x-for="category in categories" :key="category.id"><option :value="category.id" x-text="categoryLabel(category)"></option></template></select></td>
            <td class="p-4"><input x-model="plan.cost_price" type="number" min="0" step="0.01" class="w-28 rounded-lg border-slate-200"></td>
            <td class="p-4"><p class="font-medium" x-text="plan.provider_routes?.[0]?.provider_plan_id||'Draft — no route'"></p><p class="text-xs text-slate-400" x-text="plan.provider_routes?.[0]?.parent_provider_connection?.name||''"></p></td>
            <td class="p-4"><span x-text="plan.validity_in_days?`${plan.validity_in_days} days`:'—'"></span></td>
            <td class="p-4"><div class="space-y-1 text-xs"><label class="block"><input x-model="plan.visibility" true-value="1" false-value="0" type="checkbox"> Active</label><label class="block"><input x-model="plan.affiliate_visibility" true-value="1" false-value="0" type="checkbox"> Affiliates</label><label class="block"><input x-model="plan.public_visibility" true-value="1" false-value="0" type="checkbox"> Public</label></div></td>
            <td class="p-4"><button @click="save(plan)" :disabled="saving" class="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50">Save</button></td>
        </tr></template></tbody></table></div>
        <div class="flex items-center justify-between border-t border-slate-100 p-4"><button @click="load(pagination.current_page-1)" :disabled="loading||pagination.current_page<=1" class="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold disabled:opacity-40">Previous page</button><span class="text-sm text-slate-500" x-text="`Page ${pagination.current_page} of ${pagination.last_page}`"></span><button @click="load(pagination.current_page+1)" :disabled="loading||pagination.current_page>=pagination.last_page" class="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold disabled:opacity-40">Next page</button></div>
    </section>
</div>
@endsection

@push('scripts')
<script>
document.addEventListener('alpine:init',()=>Alpine.data('parentPlans',()=>({
    plans:[],categories:[],connections:[],levels:[],bulkPlans:[],form:{},mode:'single',loading:false,saving:false,search:'',notice:'',error:'',pagination:{current_page:1,last_page:1,total:0,from:0,to:0},
    urls:{data:@js(route('parent-admin.product-plans.data')),store:@js(route('parent-admin.product-plans.store')),bulk:@js(route('parent-admin.product-plans.bulk-store')),base:@js(url('/parent-admin/product-plans'))},
    get filteredPlans(){const q=this.search.toLowerCase();return this.plans.filter(p=>`${p.product_plan_name} ${p.api_id||''} ${p.product_plan_category?.product_plan_category_name||''}`.toLowerCase().includes(q))},
    get paginationText(){return this.pagination.total?`Showing ${this.pagination.from}–${this.pagination.to} of ${this.pagination.total} plans`:'No plans found'},
    categoryLabel(c){return `${c.product_plan_category_name} · ${c.network?.network_name||c.product?.product_name||'General'}`},
    levelName(id){return this.levels.find(level=>String(level.id)===String(id))?.name||'Reseller level'},
    blankPlan(){const active=this.connections.length>0&&this.levels.length>0;return {client_id:crypto.randomUUID(),product_plan_name:'',product_plan_category_id:'',api_id:'',admin_cost_price:'',cost_price:'',data_size_in_mb:'',validity_in_days:'',profit_category:'flat',commission_feature:true,upline_commission_option:'flat',upline_flat_commission:0,upline_percentage_commission:0,upline_commission_cap:1000,visibility:active,affiliate_visibility:active,public_visibility:active,route:{parent_provider_connection_id:this.connections[0]?.id||'',provider_plan_id:''},prices:this.levels.map(level=>({parent_reseller_level_id:level.id,selling_price:'',max_profit:''}))}},
    clean(plan){const copy=structuredClone(plan);delete copy.client_id;['api_id','admin_cost_price','data_size_in_mb','validity_in_days'].forEach(key=>{if(copy[key]==='')copy[key]=null});copy.prices.forEach(price=>{if(price.max_profit==='')price.max_profit=null});if(!copy.route.parent_provider_connection_id&&!copy.route.provider_plan_id)copy.route=null;return copy},
    async load(page=1){this.loading=true;this.error='';try{const {data}=await axios.get(this.urls.data,{params:{page}});this.plans=data.plans.data;this.categories=data.categories;this.connections=data.connections;this.levels=data.levels;this.pagination={current_page:data.plans.current_page,last_page:data.plans.last_page,total:data.plans.total,from:data.plans.from||0,to:data.plans.to||0};if(!this.form.product_plan_name)this.form=this.blankPlan();if(this.bulkPlans.length===0)this.bulkPlans=[this.blankPlan()]}catch(e){this.fail(e)}finally{this.loading=false}},
    openBulk(){this.mode='bulk';if(this.bulkPlans.length===0)this.bulkPlans=[this.blankPlan()]},addBulkRow(){this.bulkPlans.push(this.blankPlan())},removeBulkRow(index){this.bulkPlans.splice(index,1)},
    async createPlan(){this.saving=true;this.error='';try{const {data}=await axios.post(this.urls.store,this.clean(this.form));this.form=this.blankPlan();await this.load(1);this.show(data.message)}catch(e){this.fail(e)}finally{this.saving=false}},
    async createBulk(){this.saving=true;this.error='';try{const {data}=await axios.post(this.urls.bulk,{plans:this.bulkPlans.map(plan=>this.clean(plan))});this.bulkPlans=[this.blankPlan()];await this.load(1);this.show(data.message)}catch(e){this.fail(e)}finally{this.saving=false}},
    async save(plan){this.saving=true;this.error='';try{const {data}=await axios.patch(`${this.urls.base}/${plan.id}`,plan);Object.assign(plan,data.plan);this.show(data.message)}catch(e){this.fail(e)}finally{this.saving=false}},
    show(message){this.notice=message;setTimeout(()=>this.notice='',3500)},fail(e){this.error=Object.values(e.response?.data?.errors||{}).flat()[0]||e.response?.data?.message||'Unable to complete this action.'}
})))
</script>
@endpush
