@extends('parent-admin.layouts.app')
@section('title','Funding affiliates')
@section('heading',$provider->fundingProvider->name.' affiliates')
@section('content')
<div class="space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><a href="{{ route('parent-admin.funding-providers.index') }}" class="text-sm font-semibold text-blue-700">← Funding providers</a><form><input name="q" value="{{ $search }}" placeholder="Search affiliates" class="rounded-xl border-slate-200"><button class="rounded-xl border px-3 py-2 font-semibold">Search</button></form></div>
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p class="font-semibold">Unable to save the affiliate configuration.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50"><tr><th class="p-4">Affiliate</th><th>Management</th><th>Status</th><th>New accounts</th><th>Approval</th><th></th></tr></thead><tbody class="divide-y">@forelse($affiliates as $affiliate)@php($config=$affiliate->fundingProviderConfigurations->first())<tr><td class="p-4"><p class="font-semibold">{{ $affiliate->name }}</p><p class="text-xs text-slate-500">{{ $affiliate->contact_email }}</p></td><td><form id="funding-affiliate-{{ $affiliate->id }}" method="POST" action="{{ route('parent-admin.funding-providers.affiliates.update',[$provider,$affiliate]) }}">@csrf @method('PUT')</form><select form="funding-affiliate-{{ $affiliate->id }}" name="management_mode" class="rounded-lg border-slate-200"><option value="parent_managed" @selected(!$config || $config->management_mode==='parent_managed')>Parent managed</option><option value="affiliate_managed" @selected($config?->management_mode==='affiliate_managed')>Affiliate managed</option></select></td><td><input form="funding-affiliate-{{ $affiliate->id }}" type="hidden" name="active" value="0"><input form="funding-affiliate-{{ $affiliate->id }}" type="checkbox" name="active" value="1" @checked($config?->active)></td><td><input form="funding-affiliate-{{ $affiliate->id }}" type="hidden" name="generation_enabled" value="0"><input form="funding-affiliate-{{ $affiliate->id }}" type="checkbox" name="generation_enabled" value="1" @checked($config?->generation_enabled)></td><td>@if($config?->modeChangeRequests->isNotEmpty())@php($modeRequest=$config->modeChangeRequests->first())<p class="mb-2 text-amber-700">Pending {{ str($modeRequest->requested_mode)->headline() }}</p><div class="flex gap-1"><form method="POST" action="{{ route('parent-admin.funding-mode-requests.review',$modeRequest) }}">@csrf @method('PATCH')<button name="decision" value="approved" class="rounded bg-emerald-600 px-2 py-1 text-xs font-semibold text-white">Approve</button></form><form method="POST" action="{{ route('parent-admin.funding-mode-requests.review',$modeRequest) }}">@csrf @method('PATCH')<button name="decision" value="rejected" class="rounded bg-red-600 px-2 py-1 text-xs font-semibold text-white">Reject</button></form></div>@else<span class="text-slate-400">—</span>@endif</td><td><button form="funding-affiliate-{{ $affiliate->id }}" class="rounded-lg border px-3 py-2 font-semibold">Save</button></td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No affiliates found.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $affiliates->links() }}</div></section></div>
@endsection
