@extends('parent-admin.layouts.app')
@section('title','Manage funding banks')
@section('heading',$provider->fundingProvider->name.' banks')
@section('content')
<div class="space-y-6"><div><a href="{{ route('parent-admin.funding-providers.index') }}" class="text-sm font-semibold text-blue-700">← Funding providers</a></div>
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('parent-admin.funding-providers.banks.store',$provider) }}" class="rounded-2xl border bg-white p-6 shadow-sm">@csrf<h2 class="font-semibold">Add bank</h2><div class="mt-4 grid gap-3 lg:grid-cols-4"><input name="name" required placeholder="Bank name" class="rounded-xl border-slate-200"><input name="bank_code" required placeholder="Provider bank code" class="rounded-xl border-slate-200"><select name="rate_type" class="rounded-xl border-slate-200"><option value="flat">Flat charge</option><option value="percentage">Percentage charge</option></select><input name="rate_value" type="number" min="0" step=".01" required placeholder="Charge value" class="rounded-xl border-slate-200"><input name="percentage_cap" type="number" min="0" step=".01" placeholder="Percentage cap" class="rounded-xl border-slate-200"><input name="description" placeholder="Description" class="rounded-xl border-slate-200"><label class="flex items-center gap-2"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" checked> Active</label><label class="flex items-center gap-2"><input type="hidden" name="generation_enabled" value="0"><input type="checkbox" name="generation_enabled" value="1" checked> New accounts</label></div><button class="mt-4 rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white">Add bank</button></form>
<section class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="divide-y">@forelse($banks as $bank)<form method="POST" action="{{ route('parent-admin.funding-providers.banks.update',[$provider,$bank]) }}" class="grid items-end gap-3 p-5 lg:grid-cols-8">@csrf @method('PUT')<input name="name" value="{{ $bank->name }}" class="rounded-lg border-slate-200"><input name="bank_code" value="{{ $bank->bank_code }}" class="rounded-lg border-slate-200"><select name="rate_type" class="rounded-lg border-slate-200"><option value="flat" @selected($bank->rate_type==='flat')>Flat</option><option value="percentage" @selected($bank->rate_type==='percentage')>Percentage</option></select><input name="rate_value" value="{{ $bank->rate_value }}" type="number" step=".01" class="rounded-lg border-slate-200"><input name="percentage_cap" value="{{ $bank->percentage_cap }}" type="number" step=".01" placeholder="Cap" class="rounded-lg border-slate-200"><input type="hidden" name="description" value="{{ $bank->description }}"><label class="text-sm"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($bank->active)> Active</label><label class="text-sm"><input type="hidden" name="generation_enabled" value="0"><input type="checkbox" name="generation_enabled" value="1" @checked($bank->generation_enabled)> New accounts</label><button class="rounded-lg border px-3 py-2 font-semibold">Save</button></form>@empty<div class="p-8 text-center text-slate-500">No banks configured yet.</div>@endforelse</div></section></div>
@endsection
