@extends('parent-admin.layouts.app')
@section('title','Funding providers')
@section('heading','Funding providers')
@section('content')
<div class="space-y-6">
    @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-semibold">Available funding providers</h2><p class="mt-1 text-sm text-slate-500">Configure parent-managed credentials and webhooks. Disabling generation never invalidates existing virtual accounts.</p><div class="mt-5 grid gap-4">@foreach($catalogue as $provider)@php($saved=$providers->firstWhere('funding_provider_id',$provider->id))<form method="POST" action="{{ route('parent-admin.funding-providers.enable',$provider) }}" class="rounded-xl border p-4">@csrf<div class="flex justify-between gap-3"><div><h3 class="font-semibold">{{ $provider->name }}</h3>@if($saved)<p class="text-xs text-slate-500">Webhook: {{ url('/api/funding/webhooks/'.$provider->slug.'/'.$saved->webhook_key) }}</p>@endif</div>@if($saved)<span class="text-xs text-slate-500">{{ $saved->affiliate_configurations_count }} affiliates</span>@endif</div><div class="mt-3 grid gap-3 md:grid-cols-2">@foreach($provider->credential_fields ?? [] as $field)<input type="password" name="credentials[{{ $field }}]" placeholder="{{ str($field)->headline() }}{{ $saved ? ' (leave blank to keep)' : '' }}" class="rounded-lg border-slate-200">@endforeach<input type="password" name="webhook_secret" placeholder="Webhook signing secret{{ $saved ? ' (leave blank to keep)' : '' }}" class="rounded-lg border-slate-200"><label class="flex items-center gap-2 text-sm"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($saved?->active)> Enabled</label><label class="flex items-center gap-2 text-sm"><input type="hidden" name="generation_enabled" value="0"><input type="checkbox" name="generation_enabled" value="1" @checked($saved?->generation_enabled)> Generate new accounts</label><label class="flex items-center gap-2 text-sm"><input type="hidden" name="webhook_active" value="0"><input type="checkbox" name="webhook_active" value="1" @checked($saved?->webhook_active)> Webhook active</label></div><div class="mt-4 flex flex-wrap gap-2"><button class="rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white">Save provider</button>@if($saved)<a href="{{ route('parent-admin.funding-providers.banks.index',$saved) }}" class="rounded-lg border px-3 py-2 text-sm font-semibold">Manage banks ({{ $saved->banks_count }})</a><a href="{{ route('parent-admin.funding-providers.affiliates.index',$saved) }}" class="rounded-lg border px-3 py-2 text-sm font-semibold">Manage affiliates</a>@endif</div></form>@endforeach</div></section>
</div>
@endsection
