@extends('parent-admin.layouts.app')
@section('title','Funding providers')
@section('heading','Funding providers')
@section('content')
<div class="space-y-6">
    @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-semibold">Available funding providers</h2><p class="mt-1 text-sm text-slate-500">Disabling generation stops new virtual accounts; existing accounts remain valid.</p><div class="mt-5 grid gap-4 xl:grid-cols-2">@foreach($catalogue as $provider)@php($saved=$providers->firstWhere('funding_provider_id',$provider->id))<form method="POST" action="{{ route('parent-admin.funding-providers.enable',$provider) }}" class="rounded-xl border p-4">@csrf<h3 class="font-semibold">{{ $provider->name }}</h3><div class="mt-3 grid gap-3 md:grid-cols-2">@foreach($provider->credential_fields ?? [] as $field)<input type="password" name="credentials[{{ $field }}]" placeholder="{{ str($field)->headline() }}{{ $saved ? ' (leave blank to keep)' : '' }}" class="rounded-lg border-slate-200">@endforeach<label class="flex items-center gap-2 text-sm"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($saved?->active)> Enabled</label><label class="flex items-center gap-2 text-sm"><input type="hidden" name="generation_enabled" value="0"><input type="checkbox" name="generation_enabled" value="1" @checked($saved?->generation_enabled)> Generate new accounts</label></div><button class="mt-3 rounded-lg bg-blue-600 px-3 py-2 text-sm font-semibold text-white">Save provider</button></form>@endforeach</div></section>
    @foreach($providers as $parentProvider)<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-semibold">{{ $parentProvider->fundingProvider->name }} affiliate configurations</h2><div class="mt-4 divide-y">@foreach($affiliates as $affiliate)@php($config=$parentProvider->affiliateConfigurations->firstWhere('affiliate_id',$affiliate->id))<form method="POST" action="{{ route('parent-admin.funding-providers.affiliates.update',[$parentProvider,$affiliate]) }}" class="grid items-end gap-3 py-4 lg:grid-cols-6">@csrf @method('PUT')<div><p class="font-semibold">{{ $affiliate->name }}</p><p class="text-xs text-slate-500">{{ $affiliate->contact_email }}</p></div><label class="grid gap-1 text-xs font-semibold">Management<select name="management_mode" class="rounded-lg border-slate-200"><option value="parent_managed" @selected($config?->management_mode==='parent_managed')>Parent managed</option><option value="affiliate_managed" @selected($config?->management_mode==='affiliate_managed')>Affiliate managed</option></select></label><label class="grid gap-1 text-xs font-semibold">Bank codes<input name="bank_codes[]" value="{{ implode(',', $config?->bank_codes ?? []) }}" placeholder="9PSB" class="rounded-lg border-slate-200"></label><label class="flex items-center gap-2 pb-3 text-sm"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($config?->active)> Active</label><label class="flex items-center gap-2 pb-3 text-sm"><input type="hidden" name="generation_enabled" value="0"><input type="checkbox" name="generation_enabled" value="1" @checked($config?->generation_enabled)> New accounts</label><button class="rounded-lg border px-3 py-2 text-sm font-semibold">Save affiliate</button></form>@if($config)@foreach($config->modeChangeRequests as $modeRequest)<form method="POST" action="{{ route('parent-admin.funding-mode-requests.review',$modeRequest) }}" class="mb-3 flex flex-wrap items-center gap-2 rounded-lg bg-amber-50 p-3 text-sm">@csrf @method('PATCH')<span class="mr-auto">Mode switch requested: <strong>{{ str($modeRequest->requested_mode)->headline() }}</strong></span><button name="decision" value="approved" class="rounded-lg bg-emerald-600 px-3 py-1.5 font-semibold text-white">Approve</button><button name="decision" value="rejected" class="rounded-lg bg-red-600 px-3 py-1.5 font-semibold text-white">Reject</button></form>@endforeach @endif @endforeach</div></section>@endforeach
</div>
@endsection
