@extends('parent-admin.layouts.app')
@section('title','Affiliates')
@section('heading','Affiliate ownership')
@section('content')
<div class="space-y-5">@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-5 xl:grid-cols-2"><form method="POST" action="{{ route('parent-admin.affiliates.store') }}" class="rounded-2xl border bg-white p-5 shadow-sm">@csrf<h2 class="font-semibold">Create affiliate</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><input name="name" value="{{ old('name') }}" required placeholder="Business name" class="rounded-xl border-slate-200"><input name="slug" value="{{ old('slug') }}" required placeholder="business-slug" class="rounded-xl border-slate-200"><input name="contact_email" value="{{ old('contact_email') }}" required type="email" placeholder="Email" class="rounded-xl border-slate-200"><input name="contact_phone" value="{{ old('contact_phone') }}" required placeholder="Phone" class="rounded-xl border-slate-200"><input name="domain_url" value="{{ old('domain_url') }}" placeholder="Domain" class="rounded-xl border-slate-200"><select name="parent_reseller_level_id" required class="rounded-xl border-slate-200"><option value="">Reseller level</option>@foreach($levels as $level)<option value="{{ $level->id }}">{{ $level->name }}</option>@endforeach</select></div><button class="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 font-semibold text-white">Create affiliate</button></form>
<form method="POST" action="{{ $eligibleAffiliates->isNotEmpty() ? route('parent-admin.affiliates.attach',$eligibleAffiliates->first()) : '#' }}" x-data="{affiliate:'{{ $eligibleAffiliates->first()?->id }}',base:'{{ url('/parent-admin/affiliates') }}'}" @submit="$el.action=`${base}/${affiliate}/attach`" class="rounded-2xl border bg-white p-5 shadow-sm">@csrf<h2 class="font-semibold">Attach existing affiliate</h2><div class="mt-4 grid gap-3"><select x-model="affiliate" required class="rounded-xl border-slate-200"><option value="">Select eligible affiliate</option>@foreach($eligibleAffiliates as $affiliate)<option value="{{ $affiliate->id }}">{{ $affiliate->name }} · {{ $affiliate->contact_email }}</option>@endforeach</select><select name="parent_reseller_level_id" required class="rounded-xl border-slate-200"><option value="">Reseller level</option>@foreach($levels as $level)<option value="{{ $level->id }}">{{ $level->name }}</option>@endforeach</select></div><button @disabled($eligibleAffiliates->isEmpty()) class="mt-4 rounded-xl bg-slate-950 px-4 py-2.5 font-semibold text-white disabled:opacity-40">Attach affiliate</button></form></div>
<section class="rounded-2xl border bg-white shadow-sm"><div class="border-b p-5"><h2 class="font-semibold">Owned affiliates</h2></div><div class="divide-y">@forelse($affiliates as $affiliate)<div class="flex flex-wrap items-center justify-between gap-4 p-5"><div><p class="font-semibold">{{ $affiliate->name }}</p><p class="text-xs text-slate-500">{{ $affiliate->contact_email }} · {{ $affiliate->slug }}</p></div><div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('parent-admin.affiliates.level.update',$affiliate) }}">@csrf @method('PATCH')<select name="parent_reseller_level_id" class="rounded-lg border-slate-200 text-sm" onchange="this.form.submit()">@foreach($levels as $level)<option value="{{ $level->id }}" @selected($affiliate->parent_reseller_level_id===$level->id)>{{ $level->name }}</option>@endforeach</select></form><form method="POST" action="{{ route('parent-admin.affiliates.categories.sync',$affiliate) }}">@csrf<button class="rounded-lg border px-3 py-2 text-sm font-semibold">Sync categories</button></form></div></div>@empty<div class="p-8 text-center text-slate-500">No affiliates assigned yet.</div>@endforelse</div><div class="p-4">{{ $affiliates->links() }}</div></section></div>
@endsection
