@extends('parent-admin.layouts.app')
@section('title','Settlement wallet')
@section('heading','Affiliate settlement wallet')
@section('content')
<div class="space-y-5">
@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold">{{ $affiliate->name }}</h2><p class="text-sm text-slate-500">Business settlement balance managed by your parent workspace.</p></div><a href="{{ route('parent-admin.affiliates.index') }}" class="rounded-lg border px-3 py-2 text-sm font-semibold">Back to affiliates</a></div>
<div class="grid gap-4 md:grid-cols-3"><div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-500">Available</p><p class="mt-2 text-2xl font-bold">₦{{ number_format((float)$wallet->available_balance,2) }}</p></div><div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-500">Reserved</p><p class="mt-2 text-2xl font-bold">₦{{ number_format((float)$wallet->reserved_balance,2) }}</p></div><div class="rounded-2xl border bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-500">Status</p><p class="mt-2 text-lg font-bold capitalize">{{ $wallet->status }}</p></div></div>
<section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-semibold">Purchase processing</h3><p class="mt-1 text-sm text-slate-500">Current mode: <strong>{{ str($processingProfile->management_mode)->replace('_',' ')->title() }}</strong> · {{ str($processingProfile->processing_engine)->replace('_',' ')->title() }}</p></div>@if($processingProfile->changeRequests()->where('status','pending')->exists())<span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">Approval pending</span>@endif</div>
<form method="POST" action="{{ route('parent-admin.affiliates.processing.change-requests.store',$affiliate) }}" class="mt-4">@csrf<input type="hidden" name="processing_engine" value="multi_parent"><h4 class="text-sm font-semibold">Request processing change</h4><p class="mt-1 text-xs text-slate-500">Affiliate-managed credentials must be issued by this parent. Every change requires platform approval.</p><div class="mt-3 grid gap-3 md:grid-cols-2"><label class="text-sm font-medium">Management mode<select name="management_mode" required class="mt-1 w-full rounded-xl border-slate-200"><option value="parent_managed">Parent managed</option><option value="affiliate_managed">Affiliate managed</option></select></label><label class="text-sm font-medium">Parent API connection<select name="parent_provider_connection_id" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Not required for parent-managed</option>@foreach($processingConnections as $connection)<option value="{{ $connection->id }}">{{ $connection->name }}</option>@endforeach</select></label><label class="text-sm font-medium">API public key<input type="password" name="credentials[api_public_key]" autocomplete="new-password" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-sm font-medium">API secret key<input type="password" name="credentials[api_secret_key]" autocomplete="new-password" class="mt-1 w-full rounded-xl border-slate-200"></label></div><button class="mt-4 rounded-xl bg-slate-950 px-4 py-2.5 font-semibold text-white">Submit for approval</button></form></section>
<form method="POST" action="{{ route('parent-admin.affiliates.settlement-wallet.credit',$affiliate) }}" class="rounded-2xl border bg-white p-5 shadow-sm">@csrf<h3 class="font-semibold">Record verified funding</h3><p class="mt-1 text-sm text-slate-500">Credit only after confirming that the affiliate has paid the parent.</p><div class="mt-4 grid gap-3 md:grid-cols-3"><label class="text-sm font-medium">Amount<input name="amount" value="{{ old('amount') }}" required inputmode="decimal" placeholder="2500.00" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-sm font-medium">Reference<input name="reference" value="{{ old('reference') }}" required placeholder="BANK-TRANSFER-1001" class="mt-1 w-full rounded-xl border-slate-200"></label><label class="text-sm font-medium">Reason<input name="reason" value="{{ old('reason') }}" required placeholder="Verified bank transfer" class="mt-1 w-full rounded-xl border-slate-200"></label></div><button class="mt-4 rounded-xl bg-blue-600 px-4 py-2.5 font-semibold text-white">Credit settlement wallet</button></form>
<section class="rounded-2xl border bg-white shadow-sm"><div class="border-b p-5"><h3 class="font-semibold">Settlement ledger</h3></div><div class="overflow-x-auto"><table class="min-w-full divide-y text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Date</th><th class="px-5 py-3">Reference</th><th class="px-5 py-3">Type</th><th class="px-5 py-3">Amount</th><th class="px-5 py-3">Balance</th><th class="px-5 py-3">Reason</th></tr></thead><tbody class="divide-y">@forelse($entries as $entry)<tr><td class="px-5 py-3">{{ $entry->created_at->format('d M Y, H:i') }}</td><td class="px-5 py-3 font-medium">{{ $entry->reference }}</td><td class="px-5 py-3">{{ str($entry->entry_type)->replace('_',' ')->title() }}</td><td class="px-5 py-3 text-emerald-700">+₦{{ number_format((float)$entry->amount,2) }}</td><td class="px-5 py-3">₦{{ number_format((float)$entry->balance_after,2) }}</td><td class="px-5 py-3 text-slate-600">{{ $entry->reason }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-8 text-center text-slate-500">No settlement funding has been recorded.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $entries->links() }}</div></section>
</div>
@endsection
