<section class="space-y-5 rounded-2xl border border-slate-200 bg-slate-50 p-5">
    <div><h4 class="font-bold text-slate-900">Service endpoints</h4><p class="mt-1 text-xs text-slate-500">Define the reusable request flow once. Provider connections inherit it and may override provider-specific URLs.</p></div>
    <div class="grid gap-4 sm:grid-cols-2">
        <label class="text-sm font-medium text-slate-700">Default HTTP method<select x-model="form.settings.http_method" class="mt-2 w-full rounded-xl border-slate-200"><template x-for="method in form.capabilities.methods" :key="method"><option :value="method" x-text="method"></option></template></select></label>
        <label class="text-sm font-medium text-slate-700">Timeout seconds<input x-model.number="form.settings.timeout_seconds" type="number" min="5" max="120" class="mt-2 w-full rounded-xl border-slate-200"></label>
        <template x-for="service in selectedServices" :key="service.slug"><label class="text-sm font-medium text-slate-700"><span x-text="`${service.name} endpoint`"></span><input x-model="form.settings.endpoints[service.slug]" class="mt-2 w-full rounded-xl border-slate-200" placeholder="/api/service or https://provider.example/api/service"><span class="mt-1 block text-[11px] font-normal text-slate-400">Use a relative path when websites using this adapter have different domains.</span></label></template>
    </div>
</section>

<section x-show="selectedServices.length" class="rounded-2xl border border-slate-200 bg-white p-5">
    <div><h4 class="font-bold text-slate-900">Product configuration</h4><p class="mt-1 text-xs text-slate-500">Every service can use its own payload, headers, identifiers and response rules.</p></div>
    <div class="mt-4 flex flex-wrap gap-2"><template x-for="service in selectedServices" :key="service.slug"><button type="button" @click="activeService=service.slug" class="rounded-full border px-4 py-2 text-xs font-bold" :class="activeService===service.slug?'border-emerald-600 bg-emerald-600 text-white':'border-slate-200 text-slate-600'" x-text="service.name"></button></template></div>

    <template x-for="service in selectedServices" :key="service.slug"><div x-show="activeService===service.slug" class="mt-5 space-y-6">
        <div class="rounded-2xl bg-slate-50 p-4">
            <div class="flex items-center justify-between"><div><h5 class="font-semibold">Request mapping</h5><p class="text-xs text-slate-500">Map provider keys to runtime values, credentials or literals.</p></div><button type="button" @click="addMapping(service.slug)" class="rounded-lg border bg-white px-3 py-2 text-xs font-bold">Add mapping</button></div>
            <div class="mt-3 space-y-2"><template x-for="(row,index) in config(service.slug).request_parameters" :key="row._id"><div class="grid gap-2 md:grid-cols-[1fr_145px_1fr_auto]"><input x-model="row.key" placeholder="Provider key" class="rounded-lg border-slate-200"><select x-model="row.type" @change="mappingTypeChanged(row)" class="rounded-lg border-slate-200"><option value="runtime">Runtime</option><option value="credential">Credential</option><option value="literal">Literal</option></select><select x-show="row.type==='runtime'" x-model="row.value" class="rounded-lg border-slate-200"><template x-for="field in runtimeFields" :key="field"><option :value="field" x-text="field"></option></template></select><select x-show="row.type==='credential'" x-model="row.value" class="rounded-lg border-slate-200"><template x-for="field in form.capabilities.credential_fields" :key="field"><option :value="field" x-text="field"></option></template></select><input x-show="row.type==='literal'" x-model="row.value" placeholder="Literal value" class="rounded-lg border-slate-200"><button type="button" @click="config(service.slug).request_parameters.splice(index,1)" class="text-xs font-bold text-rose-600">Remove</button></div></template></div>
        </div>

        <div class="rounded-2xl bg-slate-50 p-4">
            <div class="flex items-center justify-between"><div><h5 class="font-semibold">Request headers</h5><p class="text-xs text-slate-500">Use credential placeholders for secret header values.</p></div><button type="button" @click="addHeader(service.slug)" class="rounded-lg border bg-white px-3 py-2 text-xs font-bold">Add header</button></div>
            <div class="mt-3 space-y-3"><template x-for="(row,index) in config(service.slug).request_headers" :key="row._id"><div class="grid gap-2 rounded-xl border bg-white p-3 md:grid-cols-2 xl:grid-cols-[1fr_130px_1fr_120px_120px_auto]"><input x-model="row.key" placeholder="Header name" class="rounded-lg border-slate-200"><select x-model="row.type" @change="mappingTypeChanged(row)" class="rounded-lg border-slate-200"><option value="credential">Credential</option><option value="runtime">Runtime</option><option value="literal">Literal</option></select><select x-show="row.type==='credential'" x-model="row.value" class="rounded-lg border-slate-200"><template x-for="field in form.capabilities.credential_fields" :key="field"><option :value="field" x-text="field"></option></template></select><select x-show="row.type==='runtime'" x-model="row.value" class="rounded-lg border-slate-200"><template x-for="field in runtimeFields" :key="field"><option :value="field" x-text="field"></option></template></select><input x-show="row.type==='literal'" x-model="row.value" placeholder="Value" class="rounded-lg border-slate-200"><input x-model="row.prefix" placeholder="Prefix" class="rounded-lg border-slate-200"><input x-model="row.suffix" placeholder="Suffix" class="rounded-lg border-slate-200"><button type="button" @click="config(service.slug).request_headers.splice(index,1)" class="text-xs font-bold text-rose-600">Remove</button></div></template></div>
        </div>

        <div class="rounded-2xl bg-slate-50 p-4"><h5 class="font-semibold">Network mapping</h5><p class="text-xs text-slate-500">Leave identifiers that do not apply to this service blank.</p><div class="mt-3 grid gap-3 sm:grid-cols-3"><template x-for="network in networkKeys" :key="network"><label class="text-xs font-semibold text-slate-500"><span x-text="network"></span><input x-model="config(service.slug).network_mapping[network]" class="mt-1 w-full rounded-lg border-slate-200" placeholder="Provider ID"></label></template></div></div>

        <div class="rounded-2xl bg-slate-50 p-4">
            <div class="flex items-center justify-between"><div><h5 class="font-semibold">Success conditions</h5><p class="text-xs text-slate-500">Every configured response condition must match.</p></div><button type="button" @click="addCondition(service.slug)" class="rounded-lg border bg-white px-3 py-2 text-xs font-bold">Add condition</button></div>
            <div class="mt-3 space-y-2"><template x-for="(row,index) in config(service.slug).success_conditions" :key="row._id"><div class="grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input x-model="row.key" placeholder="Response path" class="rounded-lg border-slate-200"><input x-model="row.value" placeholder="Expected value" class="rounded-lg border-slate-200"><button type="button" @click="config(service.slug).success_conditions.splice(index,1)" class="text-xs font-bold text-rose-600">Remove</button></div></template></div>
            <div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label class="text-xs font-semibold text-slate-500">Success message path<input x-model="config(service.slug).success_message_path" class="mt-1 w-full rounded-lg border-slate-200"></label><label class="text-xs font-semibold text-slate-500">Failure message path<input x-model="config(service.slug).failure_message_path" class="mt-1 w-full rounded-lg border-slate-200"></label><label class="text-xs font-semibold text-slate-500">Actual charge path<input x-model="config(service.slug).actual_charge_path" class="mt-1 w-full rounded-lg border-slate-200" placeholder="data.amount_charged"></label><label class="text-xs font-semibold text-slate-500">Success HTTP code<input x-model.number="config(service.slug).expected_success_code" type="number" min="100" max="599" class="mt-1 w-full rounded-lg border-slate-200"></label><label class="text-xs font-semibold text-slate-500">Failure HTTP code<input x-model.number="config(service.slug).expected_failure_code" type="number" min="100" max="599" class="mt-1 w-full rounded-lg border-slate-200"></label></div>
        </div>

        <div x-show="isValidatable(service.slug)" class="rounded-2xl border border-violet-200 bg-violet-50 p-4">
            <div class="flex items-center justify-between gap-3"><div><h5 class="font-semibold text-violet-950">Customer validation</h5><p class="text-xs text-violet-700">Confirm smartcard or meter details before purchase.</p></div><label class="flex items-center gap-2 text-xs font-bold"><input type="checkbox" :checked="hasValidation(service.slug)" @change="toggleValidation(service.slug,$event.target.checked)" class="rounded border-violet-300 text-violet-600"> Enable</label></div>
            <template x-if="hasValidation(service.slug)"><div class="mt-4 space-y-4">
                <div class="grid gap-3 sm:grid-cols-2"><label class="text-xs font-semibold text-violet-800">Validation endpoint<input x-model="config(service.slug).validation.endpoint" class="mt-1 w-full rounded-lg border-violet-200" placeholder="/api/validate-customer"></label><label class="text-xs font-semibold text-violet-800">HTTP method<select x-model="config(service.slug).validation.http_method" class="mt-1 w-full rounded-lg border-violet-200"><option>POST</option><option>GET</option></select></label></div>
                <div><div class="flex justify-between"><h6 class="text-sm font-semibold">Validation request mapping</h6><button type="button" @click="addValidationMapping(service.slug)" class="text-xs font-bold text-violet-700">Add mapping</button></div><div class="mt-2 space-y-2"><template x-for="(row,index) in config(service.slug).validation.request_parameters" :key="row._id"><div class="grid gap-2 md:grid-cols-[1fr_140px_1fr_auto]"><input x-model="row.key" placeholder="Provider key" class="rounded-lg border-violet-200"><select x-model="row.type" @change="mappingTypeChanged(row)" class="rounded-lg border-violet-200"><option value="runtime">Runtime</option><option value="credential">Credential</option><option value="literal">Literal</option></select><select x-show="row.type==='runtime'" x-model="row.value" class="rounded-lg border-violet-200"><template x-for="field in runtimeFields" :key="field"><option :value="field" x-text="field"></option></template></select><select x-show="row.type==='credential'" x-model="row.value" class="rounded-lg border-violet-200"><template x-for="field in form.capabilities.credential_fields" :key="field"><option :value="field" x-text="field"></option></template></select><input x-show="row.type==='literal'" x-model="row.value" class="rounded-lg border-violet-200"><button type="button" @click="config(service.slug).validation.request_parameters.splice(index,1)" class="text-xs font-bold text-rose-600">Remove</button></div></template></div></div>
                <div><div class="flex justify-between"><h6 class="text-sm font-semibold">Validation headers</h6><button type="button" @click="addValidationHeader(service.slug)" class="text-xs font-bold text-violet-700">Add header</button></div><div class="mt-2 space-y-2"><template x-for="(row,index) in config(service.slug).validation.request_headers" :key="row._id"><div class="grid gap-2 md:grid-cols-[1fr_140px_1fr_120px_auto]"><input x-model="row.key" placeholder="Header" class="rounded-lg border-violet-200"><select x-model="row.type" @change="mappingTypeChanged(row)" class="rounded-lg border-violet-200"><option value="credential">Credential</option><option value="runtime">Runtime</option><option value="literal">Literal</option></select><select x-show="row.type==='credential'" x-model="row.value" class="rounded-lg border-violet-200"><template x-for="field in form.capabilities.credential_fields" :key="field"><option :value="field" x-text="field"></option></template></select><select x-show="row.type==='runtime'" x-model="row.value" class="rounded-lg border-violet-200"><template x-for="field in runtimeFields" :key="field"><option :value="field" x-text="field"></option></template></select><input x-show="row.type==='literal'" x-model="row.value" class="rounded-lg border-violet-200"><input x-model="row.prefix" placeholder="Prefix" class="rounded-lg border-violet-200"><button type="button" @click="config(service.slug).validation.request_headers.splice(index,1)" class="text-xs font-bold text-rose-600">Remove</button></div></template></div></div>
                <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label class="text-xs font-semibold text-violet-800">Success response path<input x-model="config(service.slug).validation.success_message_path" class="mt-1 w-full rounded-lg border-violet-200"></label><label class="text-xs font-semibold text-violet-800">Failure response path<input x-model="config(service.slug).validation.failure_message_path" class="mt-1 w-full rounded-lg border-violet-200"></label><label class="text-xs font-semibold text-violet-800">Customer name path<input x-model="config(service.slug).validation.customer_name_path" class="mt-1 w-full rounded-lg border-violet-200"></label><label class="text-xs font-semibold text-violet-800">Customer address path<input x-model="config(service.slug).validation.customer_address_path" class="mt-1 w-full rounded-lg border-violet-200"></label></div>
                <div><div class="flex justify-between"><h6 class="text-sm font-semibold">Validation success conditions</h6><button type="button" @click="addValidationCondition(service.slug)" class="text-xs font-bold text-violet-700">Add condition</button></div><div class="mt-2 space-y-2"><template x-for="(row,index) in config(service.slug).validation.success_conditions" :key="row._id"><div class="grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input x-model="row.key" class="rounded-lg border-violet-200" placeholder="Response path"><input x-model="row.value" class="rounded-lg border-violet-200" placeholder="Expected"><button type="button" @click="config(service.slug).validation.success_conditions.splice(index,1)" class="text-xs font-bold text-rose-600">Remove</button></div></template></div></div>
            </div></template>
        </div>
    </div></template>
</section>

<details class="rounded-2xl border border-slate-200 bg-white p-5" @toggle="toggleExpert($event)"><summary class="cursor-pointer font-bold text-slate-900">Advanced JSON</summary><p class="mt-2 text-xs text-slate-500">Expert escape hatch. Paste valid JSON, apply it to populate the guided fields, then save the adapter. Unsaved JSON edits are retained even when this panel is closed.</p><textarea x-model="form.expertJson" @input="form.expertDirty = true" rows="18" class="mt-3 w-full rounded-xl border-slate-200 font-mono text-xs"></textarea><div class="mt-3 flex flex-wrap items-center gap-3"><button type="button" @click="applyExpertJson()" class="rounded-xl bg-violet-600 px-4 py-2 text-xs font-bold text-white hover:bg-violet-500">Apply JSON to guided form</button><span x-show="form.expertDirty" class="text-xs font-medium text-amber-700">JSON has unapplied changes. Saving will still use these changes.</span></div><span x-show="errors.settings" class="mt-1 block text-xs text-rose-600" x-text="firstError('settings')"></span></details>
