<?php
return  [
        "banks" =>
        ["id"=>"1", "bank" => 'Access Bank', "bank_code" => '044'],
        ["id"=>"2", "bank" =>'Citibank', "bank_code" => '023'],
        ["id"=>"3", "bank" =>'Diamond Bank', "bank_code" => '063'],
        ["id"=>"5", "bank" =>'Ecobank Nigeria', "bank_code" => '050'],
        ["id"=>"6", "bank" =>'Fidelity Bank Nigeria', "bank_code" => '070'],
        ["id"=>"7", "bank" =>'First Bank of Nigeria', "bank_code" => '011'],
        ["id"=>"8", "bank" =>'First City Monument Bank', "bank_code" => '214'],
        ["id"=>"9", "bank" =>'Guaranty Trust Bank', "bank_code" => '058'],
        ["id"=>"10", "bank" =>'Heritage Bank Plc', "bank_code" => '030'],
        ["id"=>"11", "bank" =>'Jaiz Bank', "bank_code" => '301'],
        ["id"=>"12", "bank" =>'Keystone Bank Limited', "bank_code" => '082'],
        ["id"=>"13", "bank" =>'Providus Bank Plc', "bank_code" => '101'],
        ["id"=>"14", "bank" =>'Polaris Bank', "bank_code" => '076'],
        ["id"=>"15", "bank" =>'Stanbic IBTC Bank Nigeria Limited', "bank_code" => '221'],
        ["id"=>"16", "bank" =>'Standard Chartered Bank', "bank_code" => '068'],
        ["id"=>"17", "bank" =>'Sterling Bank', "bank_code" => '232'],
        ["id"=>"18", "bank" =>'Suntrust Bank Nigeria Limited', "bank_code" => '100'],
        ["id"=>"19", "bank" =>'Union Bank of Nigeria', "bank_code" => '032'],
        ["id"=>"20", "bank" =>'United Bank for Africa', "bank_code" => '033'],
        ["id"=>"21", "bank" =>'Unity Bank Plc', "bank_code" => '215'],
        ["id"=>"22", "bank" =>'Wema Bank', "bank_code" => '035'],
        ["id"=>"23", "bank" =>'Zenith Bank', "bank_code" => '057'],
        ["id"=>"24", "bank" =>'Enterprise Bank Plc', "bank_code" => '084'],
        ["id"=>"25", "bank" =>'Mainstreet Bank Plc', "bank_code" => '014'],
        ["id"=>"26", "bank" =>'Providus Bank', "bank_code" => '101'],
        ["id"=>"27", "bank" =>'Titan Trust Bank', "bank_code" => '102'],
        ["id"=>"28", "bank" =>'Globus Bank Limited', "bank_code" => '103'],
        ["id"=>"29", "bank" =>'Parallex Bank Limited', "bank_code" => '104'],
        ["id"=>"30", "bank" =>'PremiumTrust Bank Limited', "bank_code" => '105'],
        ["id"=>"31", "bank" =>'Optimus Bank Limited', "bank_code" => '107'],
        ["id"=>"32", "bank" =>'LOTUS BANK LIMITED', "bank_code" => '303'],
        ["id"=>"33", "bank" =>'FSDH Merchant Bank LTD', "bank_code" => '501'],
        ["id"=>"34", "bank" =>'Coronation Merchant Bank Nig Ltd', "bank_code" => '559'],
        ["id"=>"35", "bank" =>'Abbey Mortgage Bank Plc', "bank_code" => '801']
    ];
 
