<?php

return [
    'site_title' => ['field_name','field_details','CrystaltechData Data Website'],
    'site_logo_alt' => ['field_name','field_details','CrystaltechData'],
    'sub_hero1' => ['field_name','field_details','Ready for quality?'],
    'hero1_part1' => ['field_name','field_details','We are committed'],
    'hero1_part2' => ['field_name','field_details','to giving you quality services'],
    'sub_hero2' => ['field_name','field_details','Competitive prices'],
    'hero2_part1' => ['field_name','field_details','Our customers love us because'],
    'hero2_part2' => ['field_name','field_details','we give the best market prices'],
    'aboutus_introduction' => ['field_name','field_details','Welcome to CrystaltechData Solutions, your trusted partner in seamless and efficient bill payment services. Founded with a vision to simplify financial transactions, CrystaltechData Solutions is dedicated to providing a convenient, secure, and user-friendly platform for managing all your bill payments in one place.'],
    'title_analytics1' => ['field_name','field_details','Happy clients'],
    'value_analytics1' => ['field_name','field_details','5K+'],
    'title_analytics2' => ['field_name','field_details','Transactions'],
    'value_analytics2' => ['field_name','field_details','10K'],
    'title_analytics3' => ['field_name','field_details','Referral bonuses'],
    'value_analytics3' => ['field_name','field_details','12M+'],
    'title_analytics4' => ['field_name','field_details','Instagram followers'],
    'value_analytics4' => ['field_name','field_details','380K'],
    'service_intro' => ['field_name','field_details','We specialize in selling data, airtime, bill payment services, cable TV subscriptions, e-pins, and much more.'],
    'data_title' => ['field_name','field_details','Data sales'],
    'data_description' => ['field_name','field_details','Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'],
    'airtime_title' => ['field_name','field_details','Airtime sales'],
    'airtime_description' => ['field_name','field_details','Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'],
    'bills_title' => ['field_name','field_details','Bills payment'],
    'bills_description' => ['field_name','field_details','Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'],
    'cable_tv_title' => ['field_name','field_details','Cable TV'],
    'cable_tv_description' => ['field_name','field_details','Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'],
    'epins_title' => ['field_name','field_details','Epins'],
    'epins_description' => ['field_name','field_details','Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'],
    'result_checker_title' => ['field_name','field_details','Result checker'],
    'result_checker_description' => ['field_name','field_details','Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from'], 
    'reviewer_name1' => ['field_name','field_details','Ralph Edwards'], 
    'reviewer_position1' => ['field_name','field_details','Market Development Manager'], 
    'review1' => ['field_name','field_details','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis, rem culpa labore voluptate
                    ullam! In, nostrum. Dicta, vero nihil. Delectus minus vitae rerum voluptatum, excepturi incidunt ut,
                    enim nam exercitationem optio ducimus!'], 
    'reviewer_name2' => ['field_name','field_details','John Doe'], 
    'reviewer_position2' => ['field_name','field_details','Doctor'], 
    'review2' => ['field_name','field_details','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis, rem culpa labore voluptate
                    ullam! In, nostrum. Dicta, vero nihil. Delectus minus vitae rerum voluptatum, excepturi incidunt ut,
                    enim nam exercitationem optio ducimus!'], 
    'reviewer_name3' => ['field_name','field_details','Oreofe Adebunmi'], 
    'reviewer_position3' => ['field_name','field_details','Business woman'], 
    'review3' => ['field_name','field_details','Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis, rem culpa labore voluptate
                    ullam! In, nostrum. Dicta, vero nihil. Delectus minus vitae rerum voluptatum, excepturi incidunt ut,
                    enim nam exercitationem optio ducimus!'],  
    'topnav_email' => ['field_name','field_details','info@CrystaltechData.com'],  
    'topnav_phone' => ['field_name','field_details','08168509044'],  
    'facebook_link' => ['field_name','field_details','https://facebook.com'],  
    'instagram_link' => ['field_name','field_details','https://instagram.com'],  
    'twitter_link' => ['field_name','field_details','https://twitter.com'],  
    'support_whatsapp_number' => ['field_name','field_details','08133494364'], 
    'physical_address' => ['field_name','field_details','No 4 Akingbade street, off admiralty, Ibadan, Oyo State'] ,
    'mobile_app_link' => ['field_name','field_details','nil'] 
];