<?php

return [
    'users' => [
        'id' => 1,
        'slug' => 'users',
        'name' => 'Users',
        'create' => 'create_users',
        'read' => 'read_users',
        'update' => 'update_users',
        'delete' => 'delete_users',
    ],
    'networks' => [
        'id' => 2,
        'slug' => 'networks',
        'name' => 'Networks',
        'create' => 'create_networks',
        'read' => 'read_networks',
        'update' => 'update_networks',
        'delete' => 'delete_networks',
    ],
    'automations' => [
        'id' => 3,
        'slug' => 'automations',
        'name' => 'Automations',
        'create' => 'create_automations',
        'read' => 'read_automations',
        'update' => 'update_automations',
        'delete' => 'delete_automations',
    ],
    'data_purchase' => [
        'id' => 4,
        'slug' => 'data_purchase',
        'name' => 'Data Purchase',
        'create' => 'create_data_purchase',
        'read' => 'read_data_purchase',
        'update' => 'update_data_purchase',
        'delete' => 'delete_data_purchase',
    ],
    'transactions' => [
        'id' => 5,
        'slug' => 'transactions',
        'name' => 'Transactions',
        'create' => 'create_transactions',
        'read' => 'read_transactions',
        'update' => 'update_transactions',
        'delete' => 'delete_transactions',
    ],
    'reseller_plans' => [
        'id' => 6,
        'slug' => 'reseller_plans',
        'name' => 'Reseller Plans',
        'create' => 'create_reseller_plans',
        'read' => 'read_reseller_plans',
        'update' => 'update_reseller_plans',
        'delete' => 'delete_reseller_plans',
    ],
    'products' => [
        'id' => 7,
        'slug' => 'products',
        'name' => 'Products',
        'create' => 'create_products',
        'read' => 'read_products',
        'update' => 'update_products',
        'delete' => 'delete_products',
    ],
    'product_categories' => [
        'id' => 8,
        'slug' => 'product_categories',
        'name' => 'Product Categories',
        'create' => 'create_product_categories',
        'read' => 'read_product_categories',
        'update' => 'update_product_categories',
        'delete' => 'delete_product_categories',
    ],
    'product_plans' => [
        'id' => 9,
        'slug' => 'product_plans',
        'name' => 'Product Plans',
        'create' => 'create_product_plans',
        'read' => 'read_product_plans',
        'update' => 'update_product_plans',
        'delete' => 'delete_product_plans',
    ],
    'product_plan_categories' => [
        'id' => 10,
        'slug' => 'product_plan_categories',
        'name' => 'Product Plan Categories',
        'create' => 'create_product_plan_categories',
        'read' => 'read_product_plan_categories',
        'update' => 'update_product_plan_categories',
        'delete' => 'delete_product_plan_categories',
    ]
];