@extends('parent-admin.layouts.app')

@section('title', 'Pricing')
@section('heading', 'Manage reseller pricing')

@section('content')
<div x-data="parentPricing()" x-init="load();loadAffiliates()" class="space-y-5">
    <div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">These normalized parent prices are ready for the future multi-parent purchase flow. The current live purchase pricing path has not been switched.</div>
    <div x-show="notice" class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800" x-text="notice"></div>
    <div x-show="error" class="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700" x-text="error"></div>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold">Reseller levels</h2><p class="text-sm text-slate-500">Keep between one and six levels. Levels already assigned to affiliates or prices cannot be removed.</p></div><div class="flex gap-2"><button @click="addLevel" :disabled="levels.length>=6" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold disabled:opacity-40">Add level</button><button @click="generateSix" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Complete six levels</button><button @click="saveLevels" class="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Save levels</button></div></div>
        <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><template x-for="(level,index) in levels" :key="level.id||`new-${index}`"><div class="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-100 text-sm font-bold" x-text="index+1"></span><input x-model="level.name" class="min-w-0 flex-1 rounded-lg border-slate-200"><button x-show="levels.length>1 && index===levels.length-1" @click="levels.splice(index,1);normalizeLevels()" class="text-sm font-semibold text-red-600">Remove</button></div></template></div>
    </section>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div class="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold">Default profit settings</h2><p class="text-sm text-slate-500">Every plan inherits the rule for its service and reseller level unless you set a custom plan price.</p></div><button @click="saveDefaults" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Save defaults</button></div>
        <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-3">Service</th><template x-for="level in levels" :key="level.id"><th class="min-w-40 p-3" x-text="level.name"></th></template></tr></thead><tbody class="divide-y"><template x-for="product in products" :key="product.id"><tr><td class="p-3 font-semibold" x-text="product.product_name"></td><template x-for="level in levels" :key="level.id"><td class="p-3"><div class="flex items-center gap-2"><input x-model="defaultFor(product,level).value" type="number" min="0" :max="defaultFor(product,level).calculation_type==='percent_discount'?100:null" step="0.01" class="w-24 rounded-lg border-slate-200"><span class="text-xs text-slate-500" x-text="defaultFor(product,level).calculation_type==='flat'?'₦ flat':'% discount'"></span></div></td></template></tr></template></tbody></table></div>
    </section>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="text-lg font-semibold">Affiliate maximum pricing</h2><p class="text-sm text-slate-500">Limit the customer profit this affiliate may configure across Customer levels 1–6. This does not change parent acquisition prices.</p></div><button @click="saveAffiliateCaps" :disabled="!selectedAffiliateId||affiliateCaps.length===0" class="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Save affiliate maximums</button></div>
        <label class="mt-5 block max-w-md text-sm font-medium">Select affiliate<select x-model="selectedAffiliateId" @change="loadAffiliateCaps" class="mt-1 w-full rounded-xl border-slate-200"><option value="">Select affiliate</option><template x-for="affiliate in affiliates" :key="affiliate.id"><option :value="affiliate.id" x-text="affiliate.name"></option></template></select></label>
        <div x-show="capViolations.length" class="mt-4 rounded-xl border border-red-200 bg-red-50 p-4"><p class="font-semibold text-red-800">These existing prices exceed the proposed maximums:</p><ul class="mt-2 space-y-1 text-sm text-red-700"><template x-for="violation in capViolations" :key="`${violation.affiliate_product_plan_id}-${violation.customer_level}`"><li x-text="`${violation.plan_name} · Customer level ${violation.customer_level}: ${violation.existing_profit} exceeds ${violation.proposed_maximum}`"></li></template></ul></div>
        <div x-show="selectedAffiliateId && affiliateCaps.length" class="mt-5 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-3">Service</th><template x-for="level in [1,2,3,4,5,6]" :key="level"><th class="min-w-32 p-3" x-text="`Customer level ${level}`"></th></template></tr></thead><tbody class="divide-y"><template x-for="product in affiliateCapProducts" :key="product.id"><tr><td class="p-3"><p class="font-semibold" x-text="product.product_name"></p><p class="text-xs text-slate-400" x-text="capFor(product,1).calculation_type==='flat'?'Flat naira maximum':'Percentage maximum'"></p></td><template x-for="level in [1,2,3,4,5,6]" :key="level"><td class="p-3"><div class="flex items-center gap-1"><span class="text-slate-400" x-text="capFor(product,level).calculation_type==='flat'?'₦':''"></span><input x-model="capFor(product,level).max_value" type="number" min="0" :max="capFor(product,level).calculation_type==='percent'?100:null" step="0.01" class="w-20 rounded-lg border-slate-200"><span class="text-slate-400" x-text="capFor(product,level).calculation_type==='percent'?'%':''"></span></div></td></template></tr></template></tbody></table></div>
        <p x-show="affiliates.length===0" class="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No affiliates are attached to this parent business yet.</p>
    </section>

    <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 class="font-semibold">Plans owned by this parent</h2><p class="text-sm text-slate-500">Review each source plan and manage its acquisition price across reseller levels 1–6.</p></div><p class="text-sm text-slate-500" x-text="paginationText"></p></div>
        <div class="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-2 xl:grid-cols-4"><input x-model.debounce.400ms="filters.search" @input="load(1)" type="search" placeholder="Search plans" class="rounded-xl border-slate-200"><select x-model="filters.product_id" @change="load(1)" class="rounded-xl border-slate-200"><option value="">All services</option><template x-for="product in products" :key="product.id"><option :value="product.id" x-text="product.product_name"></option></template></select><select x-model="filters.category_id" @change="load(1)" class="rounded-xl border-slate-200"><option value="">All networks/categories</option><template x-for="category in categories" :key="category.id"><option :value="category.id" x-text="categoryLabel(category)"></option></template></select><select x-model="filters.pricing_status" @change="load(1)" class="rounded-xl border-slate-200"><option value="">Pricing status: all</option><option value="inherited">Using default</option><option value="custom">Custom override</option></select></div>
        <div x-show="loading" x-transition class="m-4 flex items-center justify-center gap-3 rounded-xl border border-blue-200 bg-blue-50 px-4 py-5 text-sm font-medium text-blue-800"><span class="h-4 w-4 animate-spin rounded-full border-2 border-blue-600 border-t-transparent"></span> Loading parent plans and prices…</div>
        <div x-show="!loading" class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="p-4">Parent plan name</th><th class="p-4">Global source</th><th class="min-w-[680px] p-4">Reseller prices · levels 1–6</th><th class="p-4"></th></tr></thead><tbody class="divide-y divide-slate-100"><template x-for="plan in plans" :key="plan.id"><tr class="align-top"><td class="p-4"><input :value="plan.product_plan_name" readonly class="w-48 rounded-lg border-slate-200 bg-white font-medium"><p class="mt-1 text-xs capitalize text-slate-400" x-text="`${plan.profit_category||'flat'} pricing · ${plan.api_id||'no internal reference'}`"></p></td><td class="p-4"><p class="font-medium" x-text="plan.product_plan_category?.product_plan_category_name||plan.product_plan_name||'—'"></p><p class="text-xs text-slate-400" x-text="`${plan.product_plan_category?.network?.network_name||productFor(plan)?.product_name||'—'} · Provider cost ₦${plan.cost_price||'—'}`"></p></td><td class="p-4"><div class="grid min-w-[640px] grid-cols-3 gap-2"><template x-for="(level,index) in levels" :key="level.id"><label class="text-[10px] text-slate-500"><span x-text="`Level ${index+1}`"></span><div class="mt-1 flex gap-1"><input x-model="priceFor(plan,level).selling_price" @focus="customize(plan,level)" type="number" min="0" step="0.01" placeholder="Price" class="w-24 rounded-lg border-slate-200 px-2 text-sm"><input x-model="priceFor(plan,level).max_profit" @focus="customize(plan,level)" type="number" min="0" step="0.01" placeholder="Max" class="w-20 rounded-lg border-slate-200 px-2 text-sm"></div><div class="mt-1 flex items-center gap-2"><span class="rounded-full px-2 py-0.5 text-[9px] font-semibold" :class="priceFor(plan,level).custom?'bg-violet-100 text-violet-700':'bg-emerald-100 text-emerald-700'" x-text="priceFor(plan,level).custom?'Custom':'Default'"></span><button type="button" x-show="priceFor(plan,level).custom" @click="useDefault(plan,level)" class="text-[10px] font-semibold text-blue-600">Use default</button><button type="button" x-show="!priceFor(plan,level).custom" @click="customize(plan,level)" class="text-[10px] font-semibold text-blue-600">Customize</button></div><p x-show="!priceFor(plan,level).custom" class="mt-1 text-[10px] text-slate-400" x-text="defaultLabel(plan,level)"></p></label></template></div><p class="mt-3 text-[10px] text-slate-400">First input: selling price · Second input: optional maximum profit</p></td><td class="p-4"><button @click="savePrices(plan)" class="whitespace-nowrap rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Save plan prices</button></td></tr></template><template x-if="!loading&&plans.length===0"><tr><td colspan="4" class="p-12 text-center text-slate-400">No parent plans match these filters.</td></tr></template></tbody></table></div>
        <div class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-5 py-4 text-sm"><p class="text-slate-500">Page <span class="font-semibold text-slate-700" x-text="pagination.current_page"></span> of <span class="font-semibold text-slate-700" x-text="pagination.last_page"></span> · <span x-text="pagination.total"></span> matching plans</p><div class="flex gap-2"><button @click="load(pagination.current_page-1)" :disabled="loading||pagination.current_page<=1" class="rounded-lg border border-slate-200 px-3 py-2 font-semibold disabled:opacity-40">← Previous page</button><button @click="load(pagination.current_page+1)" :disabled="loading||pagination.current_page>=pagination.last_page" class="rounded-lg border border-slate-200 px-3 py-2 font-semibold disabled:opacity-40">Next page →</button></div></div>
    </section>
</div>
@endsection

@push('scripts')
<script>
document.addEventListener('alpine:init',()=>Alpine.data('parentPricing',()=>({
    levels:[],plans:[],defaults:[],products:[],categories:[],affiliates:[],selectedAffiliateId:'',affiliateCaps:[],capViolations:[],loading:false,notice:'',error:'',filters:{search:'',product_id:'',category_id:'',pricing_status:''},pagination:{current_page:1,last_page:1,total:0,from:0,to:0},
    urls:{data:@js(route('parent-admin.pricing.data')),defaults:@js(route('parent-admin.pricing.defaults.update')),affiliates:@js(route('parent-admin.pricing.affiliates.index')),levels:@js(route('parent-admin.pricing.levels.update')),generate:@js(route('parent-admin.pricing.levels.generate-six')),base:@js(url('/parent-admin/pricing/plans')),affiliateBase:@js(url('/parent-admin/pricing/affiliates'))},
    get paginationText(){return this.pagination.total ? `Showing ${this.pagination.from}–${this.pagination.to} of ${this.pagination.total} plans` : 'No plans found'},
    async load(page=1){this.loading=true;try{const {data}=await axios.get(this.urls.data,{params:{page,...this.filters}});this.levels=data.levels;this.plans=data.plans.data;this.defaults=data.defaults;this.products=data.products;this.categories=data.categories;this.pagination={current_page:data.plans.current_page,last_page:data.plans.last_page,total:data.plans.total,from:data.plans.from||0,to:data.plans.to||0};this.prepare()}catch(e){this.fail(e)}finally{this.loading=false}},
    prepare(){this.plans.forEach(plan=>{plan.price_matrix={};this.levels.forEach(level=>{const price=(plan.parent_prices||[]).find(row=>Number(row.parent_reseller_level_id)===Number(level.id));plan.price_matrix[level.id]={parent_reseller_level_id:level.id,selling_price:price?.selling_price||'',max_profit:price?.max_profit||'',custom:!!price}})})},
    priceFor(plan,level){return plan.price_matrix[level.id]||(plan.price_matrix[level.id]={parent_reseller_level_id:level.id,selling_price:'',max_profit:''})},
    productFor(plan){return this.products.find(product=>Number(product.id)===Number(plan.product_plan_category?.product_id))},
    defaultFor(product,level){let rule=this.defaults.find(row=>Number(row.product_id)===Number(product.id)&&Number(row.parent_reseller_level_id)===Number(level.id));if(!rule){rule={product_id:product.id,parent_reseller_level_id:level.id,calculation_type:['airtime','electricity'].some(word=>(product.product_name||'').toLowerCase().includes(word))?'percent_discount':'flat',value:''};this.defaults.push(rule)}return rule},
    defaultLabel(plan,level){const product=this.productFor(plan);if(!product)return 'No service default';const rule=this.defaultFor(product,level);return rule.calculation_type==='flat'?`Provider cost + ₦${rule.value}`:`${rule.value}% discount`},
    get affiliateCapProducts(){return [...new Map(this.affiliateCaps.filter(cap=>cap.product).map(cap=>[cap.product.id,cap.product])).values()]},
    capFor(product,level){return this.affiliateCaps.find(cap=>Number(cap.product_id)===Number(product.id)&&Number(cap.customer_level)===Number(level))||{}},
    async loadAffiliates(){try{const {data}=await axios.get(this.urls.affiliates);this.affiliates=data.affiliates;if(this.affiliates.length){this.selectedAffiliateId=this.affiliates[0].id;await this.loadAffiliateCaps()}}catch(e){this.fail(e)}},
    async loadAffiliateCaps(){this.capViolations=[];this.affiliateCaps=[];if(!this.selectedAffiliateId)return;try{const {data}=await axios.get(`${this.urls.affiliateBase}/${this.selectedAffiliateId}/caps`);this.affiliateCaps=data.caps}catch(e){this.fail(e)}},
    async saveAffiliateCaps(){this.error='';this.capViolations=[];try{const caps=this.affiliateCaps.map(({product_id,customer_level,calculation_type,max_value})=>({product_id,customer_level,calculation_type,max_value}));const {data}=await axios.put(`${this.urls.affiliateBase}/${this.selectedAffiliateId}/caps`,{caps});this.affiliateCaps=data.caps;this.show(data.message)}catch(e){this.capViolations=e.response?.data?.violations||[];this.fail(e)}},
    categoryLabel(category){return `${category.product_plan_category_name}${category.network?.network_name?' · '+category.network.network_name:''}`},
    customize(plan,level){const price=this.priceFor(plan,level);price.custom=true;const product=this.productFor(plan);const rule=product?this.defaultFor(product,level):null;if(rule?.calculation_type==='flat'&&plan.cost_price!==null)price.selling_price=(Number(plan.cost_price)+Number(rule.value)).toFixed(2)},
    async useDefault(plan,level){try{const {data}=await axios.delete(`${this.urls.base}/${plan.id}/levels/${level.id}`);const price=this.priceFor(plan,level);price.custom=false;price.selling_price='';price.max_profit='';this.show(data.message)}catch(e){this.fail(e)}},
    async saveDefaults(){this.error='';try{const {data}=await axios.put(this.urls.defaults,{rules:this.defaults.map(({parent_reseller_level_id,product_id,calculation_type,value})=>({parent_reseller_level_id,product_id,calculation_type,value}))});this.defaults=data.defaults;this.show(data.message)}catch(e){this.fail(e)}},
    normalizeLevels(){this.levels.forEach((level,index)=>level.position=index+1)},
    addLevel(){if(this.levels.length<6){this.levels.push({position:this.levels.length+1,name:`Level ${this.levels.length+1}`})}},
    async saveLevels(){this.error='';try{this.normalizeLevels();const {data}=await axios.put(this.urls.levels,{levels:this.levels});this.levels=data.levels;this.prepare();this.show(data.message)}catch(e){this.fail(e)}},
    async generateSix(){this.error='';try{const {data}=await axios.post(this.urls.generate);this.levels=data.levels;await this.load();this.show(data.message)}catch(e){this.fail(e)}},
    async savePrices(plan){this.error='';try{const prices=this.levels.map(level=>{const price=this.priceFor(plan,level);return {...price,inherit:!price.custom}});const {data}=await axios.put(`${this.urls.base}/${plan.id}`,{prices});plan.parent_prices=data.prices;this.prepare();this.show(data.message)}catch(e){this.fail(e)}},
    show(message){this.notice=message;setTimeout(()=>this.notice='',3500)},fail(e){this.error=Object.values(e.response?.data?.errors||{}).flat()[0]||e.response?.data?.message||'Unable to complete this action.'}
})));
</script>
@endpush
