@extends('parent-admin.layouts.app')

@section('title', 'Provider connections')
@section('heading', 'Provider connections')

@section('content')
<div x-data="providerConnections()" x-init="load()" class="space-y-5">
    <div class="rounded-2xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Configure how this parent communicates with providers. Credentials are encrypted and never displayed again after saving. Live purchases are not switched by this screen.</div>
    <div x-show="notice" class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800" x-text="notice"></div>
    <div x-show="error" class="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700" x-text="error"></div>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-lg font-semibold">Configured connections</h2><p class="text-sm text-slate-500">One connection can be primary. Other connections remain ready for later backup routing.</p></div><button @click="newConnection" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white">Add provider connection</button></div>
        <div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><template x-for="connection in connections" :key="connection.id"><button @click="edit(connection)" class="rounded-xl border border-slate-200 p-4 text-left hover:border-blue-300"><div class="flex items-center justify-between gap-2"><p class="font-semibold" x-text="connection.name"></p><div class="flex gap-1"><span x-show="connection.settings?.is_primary" class="rounded-full bg-blue-100 px-2 py-1 text-[10px] font-bold text-blue-700">PRIMARY</span><span class="rounded-full px-2 py-1 text-[10px] font-bold uppercase" :class="approvalBadge(connection.approval_status)" x-text="connection.approval_status"></span></div></div><p class="mt-1 text-xs text-slate-500" x-text="connection.provider_connection?.name"></p><p class="mt-3 truncate text-xs text-slate-400" x-text="connection.base_url||'Service endpoints only'"></p><p x-show="connection.rejection_reason" class="mt-3 text-xs font-medium text-red-600" x-text="connection.rejection_reason"></p></button></template><p x-show="connections.length===0" class="text-sm text-slate-500">No provider connection has been configured.</p></div>
    </section>

    <form x-show="editing" @submit.prevent="save" class="space-y-5">
        <div x-show="form.id" class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Changing endpoints, credentials, mappings, headers or response rules will return this connection to pending platform approval. Renaming it, changing operational status or primary preference will not.</div>
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div class="mb-5"><h2 class="font-semibold">Product request configuration</h2><p class="mt-1 text-sm text-slate-500">Each product has its own payload, headers, network IDs and response rules.</p></div>
            <div class="mb-5 flex flex-wrap gap-2"><template x-for="product in supportedServices" :key="product.slug"><button type="button" @click="selectProduct(product.slug)" class="rounded-full border px-4 py-2 text-sm font-semibold" :class="activeProduct===product.slug?'border-blue-600 bg-blue-600 text-white':'border-slate-200 bg-white text-slate-600'" x-text="product.name"></button></template></div>
            <div x-show="activeProduct" class="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-900"><span class="font-semibold" x-text="activeProductName"></span> settings are independent from every other product.</div>

        <div x-show="activeProduct" class="mt-5 space-y-5">
        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div class="mb-4"><h2 class="font-semibold">Provider information</h2><p class="text-sm text-slate-500">Select a platform-approved adapter and name this parent connection.</p></div>
            <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label class="text-sm">Approved adapter<select x-model="form.provider_connection_id" @change="applyAdapterDefaults()" required class="mt-1 w-full rounded-xl border-slate-200"><option value="">Select adapter</option><template x-for="adapter in availableAdapters" :key="adapter.id"><option :value="adapter.id" x-text="`${adapter.name} · ${adapter.adapter}${adapter.status === 'inactive' ? ' · inactive' : ''}`"></option></template></select></label><label class="text-sm">Connection name<input x-model="form.name" required class="mt-1 w-full rounded-xl border-slate-200" placeholder="Affatech Primary"></label><label class="text-sm">Base URL<input x-model="form.base_url" type="url" class="mt-1 w-full rounded-xl border-slate-200" placeholder="https://provider.example/api"></label><label class="text-sm">Status<select x-model="form.status" class="mt-1 w-full rounded-xl border-slate-200"><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>
            <label class="mt-4 flex items-center gap-2 text-sm font-medium"><input x-model="form.is_primary" type="checkbox"> Make this the primary provider connection</label>
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 class="font-semibold">Encrypted credentials</h2><p class="mt-1 text-sm text-slate-500">Leave a field blank while editing to preserve its saved value.</p>
            <div class="mt-4 grid gap-3 md:grid-cols-3"><template x-for="field in allowedCredentialFields" :key="field"><label class="text-sm capitalize"><span x-text="field.replaceAll('_',' ')"></span><input x-model="form.credentials[field]" type="password" autocomplete="new-password" class="mt-1 w-full rounded-xl border-slate-200" :placeholder="form.credential_status[field]?'Saved · enter replacement':'Enter value'"></label></template><p x-show="selectedAdapter && allowedCredentialFields.length === 0" class="text-sm text-slate-500">This adapter requires no stored credentials.</p></div>
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 class="font-semibold">Service endpoints</h2><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><template x-for="product in supportedServices" :key="product.slug"><label class="text-sm"><span x-text="`${product.name} URL`"></span><input x-model="form.settings.endpoints[product.slug]" type="url" class="mt-1 w-full rounded-xl border-slate-200" :placeholder="`https://provider.example/api/${product.slug}`"></label></template></div>
            <div class="mt-4 grid gap-3 md:grid-cols-2"><label class="text-sm">HTTP method<select x-model="form.settings.http_method" class="mt-1 w-full rounded-xl border-slate-200"><template x-for="method in allowedMethods" :key="method"><option :value="method" x-text="method"></option></template></select></label><label class="text-sm">Timeout in seconds<input x-model="form.settings.timeout_seconds" type="number" min="5" max="120" class="mt-1 w-full rounded-xl border-slate-200"></label></div>
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div class="flex items-center justify-between"><div><h2 class="font-semibold">Request mapping</h2><p class="text-sm text-slate-500">Map provider keys to runtime values, credentials or literals.</p></div><button type="button" @click="addRow('request_parameters')" class="rounded-lg border px-3 py-2 text-xs font-semibold">Add mapping</button></div>
            <div class="mt-4 space-y-2"><template x-for="(row,index) in currentProductConfig.request_parameters" :key="row.id"><div class="grid gap-2 md:grid-cols-[1fr_160px_1fr_auto]"><input x-model="row.key" required placeholder="Provider key" class="rounded-lg border-slate-200"><select x-model="row.type" class="rounded-lg border-slate-200"><option value="runtime">Runtime</option><option value="credential">Credential</option><option value="literal">Literal</option></select><select x-show="row.type==='runtime'" x-model="row.value" class="rounded-lg border-slate-200"><template x-for="field in runtimeFields"><option :value="field" x-text="field"></option></template></select><select x-show="row.type==='credential'" x-model="row.value" class="rounded-lg border-slate-200"><template x-for="field in allowedCredentialFields"><option :value="field" x-text="field"></option></template></select><input x-show="row.type==='literal'" x-model="row.value" placeholder="Static value" class="rounded-lg border-slate-200"><button type="button" @click="removeRow('request_parameters',index)" class="text-sm font-semibold text-red-600">Remove</button></div></template></div>
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div class="flex items-center justify-between"><div><h2 class="font-semibold">Request headers</h2><p class="text-sm text-slate-500">Use credential placeholders for secret header values.</p></div><button type="button" @click="addRow('request_headers')" class="rounded-lg border px-3 py-2 text-xs font-semibold">Add header</button></div>
            <div class="mt-4 space-y-2"><template x-for="(row,index) in currentProductConfig.request_headers" :key="row.id"><div class="grid gap-2 md:grid-cols-[1fr_140px_120px_1fr_auto]"><input x-model="row.key" required placeholder="Authorization" class="rounded-lg border-slate-200"><select x-model="row.type" class="rounded-lg border-slate-200"><option value="credential">Credential</option><option value="runtime">Runtime</option><option value="literal">Literal</option></select><input x-model="row.prefix" placeholder="Prefix, e.g. Bearer " class="rounded-lg border-slate-200"><select x-show="row.type==='credential'" x-model="row.value" class="rounded-lg border-slate-200"><template x-for="field in allowedCredentialFields"><option :value="field" x-text="field"></option></template></select><select x-show="row.type==='runtime'" x-model="row.value" class="rounded-lg border-slate-200"><template x-for="field in runtimeFields"><option :value="field" x-text="field"></option></template></select><input x-show="row.type==='literal'" x-model="row.value" placeholder="Static value" class="rounded-lg border-slate-200"><button type="button" @click="removeRow('request_headers',index)" class="text-sm font-semibold text-red-600">Remove</button></div></template></div>
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 class="font-semibold">Network mapping</h2><div class="mt-4 grid gap-3 md:grid-cols-4"><template x-for="network in ['MTN','GLO','AIRTEL','9MOBILE']" :key="network"><label class="text-sm"><span x-text="network"></span><input x-model="currentProductConfig.network_mapping[network]" class="mt-1 w-full rounded-xl border-slate-200" placeholder="Provider network ID"></label></template></div>
        </section>

        <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div class="flex items-center justify-between"><div><h2 class="font-semibold">Success conditions</h2><p class="text-sm text-slate-500">Every configured response condition must match.</p></div><button type="button" @click="addCondition" class="rounded-lg border px-3 py-2 text-xs font-semibold">Add condition</button></div><div class="mt-4 space-y-2"><template x-for="(row,index) in currentProductConfig.success_conditions" :key="row.id"><div class="grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input x-model="row.key" required placeholder="status or data.completed" class="rounded-lg border-slate-200"><input x-model="row.value" required placeholder="success" class="rounded-lg border-slate-200"><button type="button" @click="currentProductConfig.success_conditions.splice(index,1)" class="text-sm font-semibold text-red-600">Remove</button></div></template></div><div class="mt-4 grid gap-3 md:grid-cols-2"><label class="text-sm">Success message path<input x-model="currentProductConfig.success_message_path" required class="mt-1 w-full rounded-xl border-slate-200" placeholder="data.message"></label><label class="text-sm">Failure message path<input x-model="currentProductConfig.failure_message_path" required class="mt-1 w-full rounded-xl border-slate-200" placeholder="error.message"></label></div>
        </section>
        </div>
        </section>

        <div class="flex justify-end gap-3"><button type="button" @click="editing=false" class="rounded-xl border border-slate-200 px-5 py-3 font-semibold">Cancel</button><button :disabled="saving" class="rounded-xl bg-slate-950 px-5 py-3 font-semibold text-white disabled:opacity-50" x-text="saving?'Saving…':'Save provider connection'"></button></div>
    </form>
</div>
@endsection

@push('scripts')
<script>
document.addEventListener('alpine:init',()=>Alpine.data('providerConnections',()=>({
    connections:[],adapters:[],products:[],runtimeFields:[],credentialFields:[],editing:false,saving:false,notice:'',error:'',activeProduct:'',form:{},
    get selectedAdapter(){return this.adapters.find(adapter=>String(adapter.id)===String(this.form.provider_connection_id))||this.connections.find(connection=>connection.id===this.form.id)?.provider_connection||null},
    get availableAdapters(){const current=this.selectedAdapter;return current?.status==='inactive'?[...this.adapters.filter(adapter=>adapter.id!==current.id),current]:this.adapters},
    get supportedServices(){const supported=this.selectedAdapter?.capabilities?.services;return this.products.filter(product=>!supported||supported.includes(product.slug))},
    get allowedMethods(){return this.selectedAdapter?.capabilities?.methods||['POST','GET']},
    get allowedCredentialFields(){return this.selectedAdapter?.capabilities?.credential_fields??this.credentialFields},
    get currentProductConfig(){return this.form.settings?.product_configs?.[this.activeProduct]||this.blankProductConfig()},
    get activeProductName(){return this.supportedServices.find(product=>product.slug===this.activeProduct)?.name||''},
    urls:{data:@js(route('parent-admin.provider-connections.data')),store:@js(route('parent-admin.provider-connections.store')),base:@js(url('/parent-admin/provider-connections'))},
    blankProductConfig(){return {request_parameters:[{id:crypto.randomUUID(),key:'',type:'runtime',value:'phone_number'}],request_headers:[],network_mapping:{MTN:'',GLO:'',AIRTEL:'','9MOBILE':''},success_conditions:[{id:crypto.randomUUID(),key:'status',value:'success'}],success_message_path:'data.message',failure_message_path:'error.message',expected_success_code:200,expected_failure_code:null}},
    blank(){return {id:null,provider_connection_id:'',name:'',base_url:'',status:'active',is_primary:false,credential_status:{},credentials:{api_public_key:'',api_secret_key:'',api_password:''},settings:{http_method:'POST',timeout_seconds:30,endpoints:{},request_parameters:[{key:'legacy_phone',type:'runtime',value:'phone_number'}],request_headers:[],network_mapping:{},success_conditions:[{key:'status',value:'success'}],success_message_path:'data.message',failure_message_path:'error.message',expected_success_code:200,expected_failure_code:null,product_configs:{},bank_name:'',bank_accounts:'',support_url:''}}},
    async load(){try{const {data}=await axios.get(this.urls.data);this.connections=data.connections;this.adapters=data.adapters;this.products=data.products;this.runtimeFields=data.runtime_fields;this.credentialFields=data.credential_fields}catch(e){this.fail(e)}},
    newConnection(){this.form=this.blank();this.editing=true;window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})},
    edit(connection){this.form=this.blank();Object.assign(this.form,{id:connection.id,provider_connection_id:connection.provider_connection_id,name:connection.name,base_url:connection.base_url||'',status:connection.status,is_primary:!!connection.settings?.is_primary,credential_status:connection.credential_status});this.form.settings={...this.form.settings,...structuredClone(connection.settings||{}),endpoints:{...this.form.settings.endpoints,...(connection.settings?.endpoints||{})},product_configs:{...(connection.settings?.product_configs||{})}};this.ensureProductConfigs(true);this.editing=true},
    applyAdapterDefaults(){if(!this.allowedMethods.includes(this.form.settings.http_method))this.form.settings.http_method=this.allowedMethods[0]||'POST';this.ensureProductConfigs(false)},
    ensureProductConfigs(useLegacy=false){this.supportedServices.forEach(product=>{if(!this.form.settings.product_configs[product.slug]){const config=this.blankProductConfig();if(useLegacy){['request_parameters','request_headers','network_mapping','success_conditions','success_message_path','failure_message_path','expected_success_code','expected_failure_code'].forEach(key=>{if(this.form.settings[key]!==undefined)config[key]=structuredClone(this.form.settings[key])})}this.form.settings.product_configs[product.slug]=config}['request_parameters','request_headers','success_conditions'].forEach(key=>this.form.settings.product_configs[product.slug][key]=(this.form.settings.product_configs[product.slug][key]||[]).map(row=>({...row,id:row.id||crypto.randomUUID()})));this.form.settings.product_configs[product.slug].network_mapping={MTN:'',GLO:'',AIRTEL:'','9MOBILE':'',...(this.form.settings.product_configs[product.slug].network_mapping||{})}});this.activeProduct=this.supportedServices[0]?.slug||''},
    selectProduct(slug){this.activeProduct=slug},
    approvalBadge(status){return status==='approved'?'bg-emerald-100 text-emerald-700':status==='rejected'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'},
    addRow(key){this.currentProductConfig[key].push({id:crypto.randomUUID(),key:'',type:key==='request_headers'?'credential':'runtime',value:key==='request_headers'?'api_public_key':'phone_number',...(key==='request_headers'?{prefix:'',suffix:''}:{})})},removeRow(key,index){this.currentProductConfig[key].splice(index,1)},addCondition(){this.currentProductConfig.success_conditions.push({id:crypto.randomUUID(),key:'',value:''})},
    payload(){const copy=structuredClone(this.form);delete copy.id;delete copy.credential_status;Object.values(copy.settings.product_configs||{}).forEach(config=>['request_parameters','request_headers','success_conditions'].forEach(key=>config[key]=(config[key]||[]).map(({id,...row})=>row)));return copy},
    async save(){this.saving=true;this.error='';try{const method=this.form.id?'put':'post',url=this.form.id?`${this.urls.base}/${this.form.id}`:this.urls.store;const {data}=await axios({method,url,data:this.payload()});this.show(data.message);this.editing=false;await this.load()}catch(e){this.fail(e)}finally{this.saving=false}},
    show(message){this.notice=message;setTimeout(()=>this.notice='',4000)},fail(e){this.error=Object.values(e.response?.data?.errors||{}).flat()[0]||e.response?.data?.message||'Unable to complete this action.'}
})));
</script>
@endpush
