<?php
namespace App\Http\Controllers\ParentAdmin;
use App\Http\Controllers\Controller;use App\Models\ParentProviderConnection;use App\Models\ProductPlanCategory;use App\Services\ParentAdmin\ParentCatalogService;use Illuminate\Http\Request;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
class ProductPlanImportController extends Controller{
 const HEADERS=['product_plan_name','category_name_reference','product_plan_category_id','connection_name_reference','parent_provider_connection_id','provider_plan_id','internal_reference','provider_cost','active','affiliate_visible','public_visible','level_1_price','level_2_price','level_3_price','level_4_price','level_5_price','level_6_price'];
 function template(Request $r){$p=$r->user('parent_admin')->parentBusiness;$connections=$p->providerConnections()->where('status','active')->where('approval_status','approved')->with('providerConnection:id,name')->orderBy('name')->get();$cats=ProductPlanCategory::with(['product:id,product_name','network:id,network_name'])->orderBy('id')->get();return response()->streamDownload(function()use($connections,$cats){$f=fopen('php://output','w');fputcsv($f,self::HEADERS);foreach($connections as $connection){foreach($cats as $cat){$categoryName=collect([$cat->product?->product_name,$cat->network?->network_name,$cat->product_plan_category_name])->filter()->unique()->implode(' · ');$connectionName=collect([$connection->name,$connection->providerConnection?->name])->filter()->unique()->implode(' · ');fputcsv($f,['',$categoryName,$cat->id,$connectionName,$connection->id,'','','',0,0,0,'','','','','','']);}}fclose($f);},'product-plans-template.csv');}
 function preview(Request $r){$r->validate(['plans_csv'=>['required','file','mimes:csv,txt','max:4096']]);$p=$r->user('parent_admin')->parentBusiness;$f=fopen($r->file('plans_csv')->getRealPath(),'r');$h=array_map('trim',fgetcsv($f)?:[]);if($h!==self::HEADERS)throw ValidationException::withMessages(['plans_csv'=>'Download and use the current CSV template.']);$rows=[];$errors=[];$line=1;while(($v=fgetcsv($f))!==false){$line++;$row=array_combine($h,array_slice(array_pad($v,count($h),null),0,count($h)));if(blank($row['product_plan_name']))continue;try{$rows[]=$this->row($p,$row,$line);}catch(ValidationException $e){$errors[$line]=collect($e->errors())->flatten()->implode(' ');}}fclose($f);if($errors||!$rows)return back()->withErrors(['plans_csv'=>$errors?'Correct the listed CSV rows.':'No completed rows found.'])->with('import_errors',$errors);$token=(string)Str::uuid();$r->session()->put("plan_import.$token",['parent'=>$p->id,'rows'=>$rows,'expires'=>now()->addMinutes(30)->timestamp]);return view('parent-admin.product-plans.import-preview',compact('rows','token'));}
 function confirm(Request $r,ParentCatalogService $catalog){$r->validate(['token'=>['required','uuid']]);$payload=$r->session()->pull('plan_import.'.$r->token);$p=$r->user('parent_admin')->parentBusiness;abort_unless($payload&&$payload['parent']===$p->id&&$payload['expires']>=time(),410,'Import preview expired.');$plans=$catalog->createPlans($p,$payload['rows']);return redirect()->route('parent-admin.product-plans.index')->with('success',$plans->count().' plans imported.');}
 private function row($p,$r,$line){$cat=ProductPlanCategory::find($r['product_plan_category_id']);$connection=ParentProviderConnection::whereKey($r['parent_provider_connection_id'])->where('parent_business_id',$p->id)->where('status','active')->where('approval_status','approved')->first();$levels=$p->resellerLevels()->where('status','active')->orderBy('position')->get();$bad=[];if(!$cat)$bad[]="Row $line has an invalid category.";if(!$connection)$bad[]="Row $line has an invalid or cross-parent connection.";if(blank($r['provider_plan_id'])||!is_numeric($r['provider_cost']))$bad[]="Row $line requires provider plan ID and numeric cost.";if($levels->count()!==6)$bad[]='Exactly six active reseller levels are required.';foreach(range(1,6)as$i)if(!is_numeric($r["level_{$i}_price"]))$bad[]="Row $line requires level $i price.";if($bad)throw ValidationException::withMessages(['row'=>$bad]);return['product_plan_name'=>trim($r['product_plan_name']),'product_plan_category_id'=>$cat->id,'api_id'=>blank($r['internal_reference'])?null:trim($r['internal_reference']),'admin_cost_price'=>$r['provider_cost'],'cost_price'=>$r['provider_cost'],'profit_category'=>'flat','commission_feature'=>false,'upline_commission_option'=>'flat','upline_percentage_commission'=>0,'upline_flat_commission'=>0,'upline_commission_cap'=>0,'visibility'=>filter_var($r['active'],FILTER_VALIDATE_BOOL),'affiliate_visibility'=>filter_var($r['affiliate_visible'],FILTER_VALIDATE_BOOL),'public_visibility'=>filter_var($r['public_visible'],FILTER_VALIDATE_BOOL),'route'=>['parent_provider_connection_id'=>$connection->id,'provider_plan_id'=>trim($r['provider_plan_id'])],'prices'=>$levels->values()->map(fn($l,$i)=>['parent_reseller_level_id'=>$l->id,'selling_price'=>$r['level_'.($i+1).'_price'],'max_profit'=>null])->all()];}
}
