@extends('layouts.app')
@section('content')
<div class="main-content"><div class="container-fluid py-6"><div class="mb-6"><h1 class="text-2xl font-bold">Affiliate funding providers</h1><p class="text-sm text-slate-500">Configure your own provider details or request a management-mode switch from your parent business.</p></div>
@if(session('success'))<div class="mb-4 rounded-lg bg-green-50 p-3 text-green-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="mb-4 rounded-lg bg-red-50 p-3 text-red-800"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-5 lg:grid-cols-2">@forelse($configs as $config)@php($provider=$config->parentFundingProvider->fundingProvider)<section class="rounded-xl border bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><h2 class="font-semibold">{{ $provider->name }}</h2><p class="text-xs text-slate-500">{{ str($config->management_mode)->headline() }}</p></div><span class="rounded-full px-2 py-1 text-xs {{ $config->generation_enabled ? 'bg-green-100 text-green-700' : 'bg-slate-100 text-slate-600' }}">{{ $config->generation_enabled ? 'Generation enabled' : 'Generation disabled' }}</span></div>
<form method="POST" action="{{ route('admin.affiliate-funding-providers.update',$config) }}" class="mt-4 grid gap-3">@csrf @method('PUT')@foreach($provider->credential_fields ?? [] as $field)<input type="password" name="credentials[{{ $field }}]" placeholder="{{ str($field)->headline() }} (leave blank to keep)" class="rounded-lg border-slate-200">@endforeach<input name="bank_codes[]" value="{{ implode(',', $config->bank_codes ?? []) }}" placeholder="Bank code" class="rounded-lg border-slate-200"><button class="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Save my details</button></form>
@if($config->modeChangeRequests->isNotEmpty())<p class="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Switch to {{ str($config->modeChangeRequests->first()->requested_mode)->headline() }} is awaiting parent approval.</p>@else<form method="POST" action="{{ route('admin.affiliate-funding-providers.mode-request',$config) }}" class="mt-3">@csrf<input type="hidden" name="requested_mode" value="{{ $config->management_mode === 'parent_managed' ? 'affiliate_managed' : 'parent_managed' }}"><button class="text-sm font-semibold text-blue-700">Request switch to {{ $config->management_mode === 'parent_managed' ? 'affiliate managed' : 'parent managed' }}</button></form>@endif</section>@empty<div class="rounded-xl border bg-white p-6 text-slate-500">Your parent has not enabled any funding provider for this affiliate.</div>@endforelse</div></div></div>
@endsection
