@extends('layouts.app')
@section('content')
<div class="main-content"><div class="container-fluid py-6"><div class="mb-6"><h1 class="text-2xl font-bold">Affiliate funding providers</h1><p class="text-sm text-slate-500">Manage your own provider credentials, webhook and bank-level customer charges.</p></div>
@if(session('success'))<div class="mb-4 rounded-lg bg-green-50 p-3 text-green-800">{{ session('success') }}</div>@endif @if($errors->any())<div class="mb-4 rounded-lg bg-red-50 p-3 text-red-800">{{ $errors->first() }}</div>@endif
<div class="grid gap-5">@forelse($configs as $config)@php($provider=$config->parentFundingProvider->fundingProvider)<section class="rounded-xl border bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="font-semibold">{{ $provider->name }}</h2><p class="text-xs text-slate-500">{{ str($config->management_mode)->headline() }}</p></div><span class="rounded-full px-2 py-1 text-xs {{ $config->generation_enabled ? 'bg-green-100 text-green-700' : 'bg-slate-100 text-slate-600' }}">{{ $config->generation_enabled ? 'Generation enabled' : 'Generation disabled' }}</span></div>
@if($config->management_mode==='parent_managed')<div class="mt-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-800">API credentials, webhook signing and effective bank charges are controlled by your parent. You may prepare your affiliate-managed configuration before requesting a switch.</div>@endif
<form method="POST" action="{{ route('admin.affiliate-funding-providers.update',$config) }}" class="mt-4">@csrf @method('PUT')<div class="grid gap-3 md:grid-cols-3">@foreach($provider->credential_fields ?? [] as $field)<input type="password" name="credentials[{{ $field }}]" placeholder="{{ str($field)->headline() }} (leave blank to keep)" class="rounded-lg border-slate-200">@endforeach<input type="password" name="webhook_secret" placeholder="Webhook signing secret (leave blank to keep)" class="rounded-lg border-slate-200"><label class="flex items-center gap-2"><input type="hidden" name="webhook_active" value="0"><input type="checkbox" name="webhook_active" value="1" @checked($config->webhook_active)> Webhook active</label></div><p class="mt-2 break-all text-xs text-slate-500">Webhook URL: {{ url('/api/funding/webhooks/'.$provider->slug.'/'.$config->webhook_key) }}</p>
<div class="mt-5 overflow-x-auto"><table class="w-full min-w-[800px] text-left text-sm"><thead class="bg-slate-50"><tr><th class="p-3">Bank</th><th>Charge type</th><th>Value</th><th>Percentage cap</th><th>Active</th><th>New accounts</th></tr></thead><tbody class="divide-y">@foreach($config->parentFundingProvider->banks as $index=>$parentBank)@php($setting=$config->banks->firstWhere('parent_funding_provider_bank_id',$parentBank->id))<tr><td class="p-3"><p class="font-semibold">{{ $parentBank->name }}</p><p class="text-xs text-slate-500">{{ $parentBank->bank_code }}</p><input type="hidden" name="banks[{{ $index }}][parent_funding_provider_bank_id]" value="{{ $parentBank->id }}"></td><td><select name="banks[{{ $index }}][rate_type]" class="rounded-lg border-slate-200"><option value="flat" @selected(($setting?->rate_type ?? 'flat')==='flat')>Flat</option><option value="percentage" @selected($setting?->rate_type==='percentage')>Percentage</option></select></td><td><input name="banks[{{ $index }}][rate_value]" value="{{ $setting?->rate_value ?? 0 }}" type="number" min="0" step=".01" class="w-28 rounded-lg border-slate-200"></td><td><input name="banks[{{ $index }}][percentage_cap]" value="{{ $setting?->percentage_cap }}" type="number" min="0" step=".01" class="w-28 rounded-lg border-slate-200"></td><td><input type="hidden" name="banks[{{ $index }}][active]" value="0"><input type="checkbox" name="banks[{{ $index }}][active]" value="1" @checked($setting?->active)></td><td><input type="hidden" name="banks[{{ $index }}][generation_enabled]" value="0"><input type="checkbox" name="banks[{{ $index }}][generation_enabled]" value="1" @checked($setting?->generation_enabled)></td></tr>@endforeach</tbody></table></div><button class="mt-4 rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Save my funding configuration</button></form>
@if($config->modeChangeRequests->isNotEmpty())<p class="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Switch to {{ str($config->modeChangeRequests->first()->requested_mode)->headline() }} is awaiting parent approval.</p>@else<form method="POST" action="{{ route('admin.affiliate-funding-providers.mode-request',$config) }}" class="mt-3">@csrf<input type="hidden" name="requested_mode" value="{{ $config->management_mode === 'parent_managed' ? 'affiliate_managed' : 'parent_managed' }}"><button class="text-sm font-semibold text-blue-700">Request switch to {{ $config->management_mode === 'parent_managed' ? 'affiliate managed' : 'parent managed' }}</button></form>@endif</section>@empty<div class="rounded-xl border bg-white p-6 text-slate-500">Your parent has not enabled any funding provider for this affiliate.</div>@endforelse</div></div></div>
@endsection
